### ISSUE TITLE
Cannot read property zxing of undefined

### ISSUE THREAD

**Issue by niekert** [EddyVerbruggen/nativescript-barcodescanner#1]
Hey,

I am trying to use the barcode scanner module but I'm getting the error 
`"Cannot read property zxing of undefined"`

It probably has to do with me not importing the zxing library correctly. I downloaded the zxing core jar from http://central.maven.org/maven2/com/google/zxing/core/3.2.0/core-3.2.0.jar and added it to my NativeScript project under /app/lib/Android/core-3.2.0.jar

Is there anything I'm missing here? Thank you!

**Comment by EddyVerbruggen** [comment]
Hi,

That's the reason I'd like to create a full-swing plugin before publishing this to npm: the setup should be completely automacted :)

You need the LibraryProject, I will update this repo today to include it, and adjust the readme. That should get you up and running. Watch this space ;)

**Comment by niekert** [comment]
Thank you! I'll keep an eye out on the repo.

**Comment by EddyVerbruggen** [comment]
Hi @niekert, please go ahead and use v 0.0.1 of this module.
Make sure to follow the steps in the readme precisely.

I will improve the installation procedure soon, but this is it for today.

**Comment by niekert** [comment]
Hi Eddy,

The instructions you posted worked for me. Thanks!

**Comment by Mararesliu** [comment]
use tns plugin add nativescript-barcodescanner
on ios platform lib/ios will auto create
on android platform  not lib/android,
ios can call scan
android "Cannot read property zxing of undefined".

**Comment by meiriko** [comment]
One thing that helped me, remove the app from your phone and run the "tns run..." again, probably the re-installation is required for permissions.
