### ISSUE TITLE
IOS Scanner Area or red line

### ISSUE THREAD

**Issue by ghost** [EddyVerbruggen/nativescript-barcodescanner#104]
If I have more barcode in A4 page I can't scan because there is no red line where the scanner area is active. Can I change area? Or can I get the red line? Android is fine.
Thanx

**Comment by EddyVerbruggen** [comment]
Well there is the big square in the center, right? I'm not sure how a red line will help..

**Comment by bumbella** [comment]
Android has a redline laserline in scanner area.
I have problem if more barcode in A4 page. The scanner area is too big.
Can I change scanner area height?
Thanx for your help.
Bumbella

**Comment by paweldziura** [comment]
Actually red line is helping. It's just easier to scan with line parallel to wide barcodes.

**Comment by EddyVerbruggen** [comment]
Using https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/ML_KIT.md#barcode-scanning you can overlay anything you want on top of the scanner UI (as demonstrated in the demo-ng app in that repo).
