### ISSUE TITLE
Display scanner within a layout

### ISSUE THREAD

**Issue by Burgov** [EddyVerbruggen/nativescript-barcodescanner#105]
I want to display the scan results directly below the camera view. However the scanner seems to always open fullscreen and I can't really find a way around that. Is there any way to do it?

**Comment by renestalder** [comment]
Quite similar question I asked in #54. Didn't found a solution yet.

**Comment by EddyVerbruggen** [comment]
For anyone reading this based on the issue title: it's supported on iOS by this plugin, and on both platforms when using https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/ML_KIT.md#barcode-scanning
