### ISSUE TITLE
Please add DataMatrix to iOS

### ISSUE THREAD

**Issue by mattesnom** [EddyVerbruggen/nativescript-barcodescanner#106]
Hi Eddy,

could you please add DataMatrix to your barcodescanner.ios.ts:

in line 193 you could add:

            else if (format === "DATA_MATRIX") types.push(AVMetadataObjectTypeDataMatrixCode);

and in line 195 you could add 

           AVMetadataObjectTypeDataMatrixCode 

to the types array.

Thank you
Mattes

**Comment by EddyVerbruggen** [comment]
Good idea, thanks!

I'll also add ITF(14) for iOS while I'm at it.

**Comment by EddyVerbruggen** [comment]
Available with 2.6.1.
