### ISSUE TITLE
App freezes/delays (~4000ms) after barcodescanner closes

### ISSUE THREAD

**Issue by felipebernardes** [EddyVerbruggen/nativescript-barcodescanner#107]
Hey everyone,

I'm having performance issues right after barcodescanner closes on android.

Although my (Angular +NS) App does nothing after scanning, the screen freezes for 3~4 seconds before focusing back on a TextField I have on the view.

I believe this is due android activity switch issue, but I'm not sure.

Does anybody had a similar problem or have any thought on how can I improve the plugin?

Thanks in advance

**Comment by EddyVerbruggen** [comment]
I have never seen this behaviour but if you can replicate it in a fresh hello world app and share the repo, then please reopen this issue and I'll take a look.

**Comment by hamdiwanis** [comment]
I have the same issue, plus I show an alert on scanner closing and it disappears after microsecond, i tested it on my android 6.0 phone, here is a repo of it. 
https://github.com/hamdiwanis/nativescript-barcodescanner-frezzing-issue
thanks

**Comment by isaacfi** [comment]
I have the same issue. This is the example, you have to start to scan and you can cancel or scan the barcode, then press constantly the "Get Delay" button to get the time in milliseconds.

[barcodeTest.zip](https://github.com/EddyVerbruggen/nativescript-barcodescanner/files/1949382/barcodeTest.zip)

Regards
