### ISSUE TITLE
Scan error after permission granted

### ISSUE THREAD

**Issue by ikhsan017** [EddyVerbruggen/nativescript-barcodescanner#109]
Dear Eddy,

Thanks for building this plugin, I just try to implement this plugin in my tns-angular project.

Just before scan performed, it ask for camera permission, but after it granted, the following error shown up

```
No scan. Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
    android.support.v4.content.LocalBroadcastManager.getInstance(LocalBroadcastManager.java:102)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
    com.tns.Runtime.callJSMethod(Runtime.java:953)
    com.tns.Runtime.callJSMethod(Runtime.java:937)
    com.tns.Runtime.callJSMethod(Runtime.java:929)
    com.tns.gen.java.lang.Object_frnal_ts_helpers_l58_c38__ClickListenerImpl.onClick(Object_frnal_ts_helpers_l58_c38__ClickListenerImpl.java:12)
    android.view.View.performClick(View.java:5340)
    android.view.View$PerformClick.run(View.java:21610)
    android.os.Handler.handleCallback(Handler.java:815)
    android.os.Handler.dispatchMessage(Handler.java:104)
    android.os.Looper.loop(Looper.java:207)
    android.app.ActivityThread.main(ActivityThread.java:5763)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

here is my scanner code
```
scanQRCode() {
        console.log("scanning");

        this.scanner.scan({
            formats: "QR_CODE",
            message: "Use the volume buttons for extra light",
            showFlipCameraButton: true,   // default false
            showTorchButton: true,        // default false
            closeCallback: () => { console.log("Scanner closed") },
            resultDisplayDuration: 500
        }).then((result) => {
              // Note that this Promise is never invoked when a 'continuousScanCallback' function is provided
            alert({
                title: "Scan result",
                message: "Format: " + result.format + ",\nValue: " + result.text,
                okButtonText: "OK"
            });
            },
            (errorMessage) => {
                console.log("No scan. " + errorMessage);
            }
        );
    }

```

**Comment by EddyVerbruggen** [comment]
Hi! At what point do you call `scanQRCode`? Do you trigger it from a button, or during app startup? In case of the latter try to move the code to your first viewcontroller, or wrap it in a `setTimeout`.

**Comment by ikhsan017** [comment]
Hi Eddy, 

scanQRCode was assigned on (tap) event

I found out that your plugin search for ```com.tns.NativescriptApplication```, while on my project, I already extend it as ```com.mycompany.CustomApplication```, changing the hardcoded application name solve my issue.

any workaround for custom application name? its on barcodescanner.android.js:127 and barcodescanner.android.js:153

**Comment by EddyVerbruggen** [comment]
Hmm, should be fixable. Can you share details on how to recreate the problem?

**Comment by ikhsan017** [comment]
ok, 

*create new application based on angular-drawer template
*add nativescript-barcodescanner plugin
*extends application and activity to custom application and activity based on https://docs.nativescript.org/runtimes/android/advanced-topics/extend-application-activity

and the above error shown

**Comment by EddyVerbruggen** [comment]
Thanks!

Can you edit the `.js` file in `node_modules` and change `com.tns.NativescriptApplication` to `appModule.android.foregroundActivity`? (remove the platforms/android folder so it's picked up, or use `tns run android --syncAllFiles`).

**Comment by ikhsan017** [comment]
I got this error ```No scan. ReferenceError: apppModule is not defined```

**Comment by EddyVerbruggen** [comment]
`apppModule` --> `appModule`?

**Comment by ikhsan017** [comment]
ah, sorry, my bad

I got this instead
```No scan. TypeError: appModule.android.foregroundActivity.getInstance is not a function```

**Comment by hugoserrana** [comment]
PR:
https://github.com/EddyVerbruggen/nativescript-barcodescanner/pull/161

**Comment by EddyVerbruggen** [comment]
Thanks! 👍
