### ISSUE TITLE
Android Build issue

### ISSUE THREAD

**Issue by AlexandreKilian** [EddyVerbruggen/nativescript-barcodescanner#11]
I currently am facing this issue when trying to run/emulate on android (iOS works fine)

> :processNativescript-barcodescannerDebugResources FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':processNativescript-barcodescannerDebugResources'.
> > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/local/Cellar/android-sdk/24.4.1_1/build-tools/23.0.2/aapt'' finished with non-zero exit value 1

tns version 1.7.0

**Comment by EddyVerbruggen** [comment]
Can you try this (just tried with success on Android with NS 1.7.0)?

```
git clone https://github.com/EddyVerbruggen/nativescript-barcodescanner-demo
cd cd nativescript-barcodescanner-demo/BarcodeScanner
tns install
tns build android
tns run android
```

**Comment by AlexandreKilian** [comment]
I don't know what it was, I started up a new project, and suddently it worked... you can close this issue...
