### ISSUE TITLE
App freezes for a while after barcodescanner closes 

### ISSUE THREAD

**Issue by hamdiwanis** [EddyVerbruggen/nativescript-barcodescanner#110]
I'm having performance issues right after barcodescanner closes on android with nativescript and angular
the screen freezes for a couple of seconds seconds after close. plus I show an alert on scanner closing and it disappears after microsecond, i tested it on my android 6.0 phone, here is a repo of it.
https://github.com/hamdiwanis/nativescript-barcodescanner-frezzing-issue
thanks

**Comment by EddyVerbruggen** [comment]
Is there a difference if you wrap [this bit](https://github.com/hamdiwanis/nativescript-barcodescanner-frezzing-issue/blob/704fa3ecbc44467f39f84ad29b4f9b51750e0d00/app/app.component.ts#L23-L27) in a timeout of half a second, or just console.log it?

**Comment by hamdiwanis** [comment]
actually yes I have tried that and this seems to show the alert but the app still freezes and you cant dismiss the alert for a couple of seconds.

**Comment by EddyVerbruggen** [comment]
Can you get the alert out of the equation? Does it still freeze?

**Comment by hamdiwanis** [comment]
also tried that I removed all code in "then" and it still does.

**Comment by EddyVerbruggen** [comment]
Then I have no idea really. The plugin isn't doing anything at that point.

Only a longshot left: if you're on recent version of NativeScript you can try adding [this](https://github.com/EddyVerbruggen/nativescript-pluginshowcase/blob/fdc07e02505305a4bbd664b26f2eee27851ba45a/app/package.json#L4)? Make sure you're editing the correct package.json file!

**Comment by hamdiwanis** [comment]
ok I will try it, the issue is the app does not do anything at all I made it for testing the problem and the app has nothing but the plugin so it must be the reason. thanks for your help.

**Comment by EddyVerbruggen** [comment]
I'd guess it's Android cleaning up some resources.. perhaps Google it a bit?

**Comment by hamdiwanis** [comment]
I started here and found out there was another issue closed with the same problem so thought to point out, will do thanks again.

**Comment by hamdiwanis** [comment]
adding "markingMode": "none" did not help, also I get this in the console right after the scanner closes.
```
JS: >> activity result: @ 1505984978379
09-21 11:09:41.697 19363 19363 E WindowManager:         at com.tns.Runtime.callJSMethodNative(Native Method)
09-21 11:09:41.697 19363 19363 E WindowManager:         at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
09-21 11:09:41.697 19363 19363 E WindowManager:         at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
09-21 11:09:41.697 19363 19363 E WindowManager:         at com.tns.Runtime.callJSMethod(Runtime.java:953)
09-21 11:09:41.697 19363 19363 E WindowManager:         at com.tns.Runtime.callJSMethod(Runtime.java:937)
09-21 11:09:41.697 19363 19363 E WindowManager:         at com.tns.Runtime.callJSMethod(Runtime.java:929)
```

**Comment by EddyVerbruggen** [comment]
OK, unfortunately, that's not a really useful stacktrace.

Not sure what I can do to help except Googling a bit about broader freeze behavior when closing a camera/scanner activity.

**Comment by hamdiwanis** [comment]
I appreciate your help I will do my search too.

**Comment by hamdiwanis** [comment]
I just used setTimeout with a delay of one ten's of a second so it's not noticeable with using enableProdMode() in main.aot.ts , with "markingMode": "none" and it works fine. hope it helps someone with the same problem.
also the stack I showed you stopped from appearing every time the scanner closes.

**Comment by EddyVerbruggen** [comment]
Can you pinpoint what the change was exactly that made the difference?

**Comment by hamdiwanis** [comment]
I think it will come too markingMode and enableProdMode although I tried each one alone and the problem was still there, but using them together seems to work fine, and as the problem never appeared with native script with js or ts but only with angular so I suppose enableProdMode made the difference.

**Comment by EddyVerbruggen** [comment]
Thank you!

**Comment by henrychavez** [comment]
@hamdiwanis can you please tell me where do i have to set the marking mode?

I already set the enableProdMode() in main.aot.ts and I don't know if I have to set a timeout to call the scanner

**Comment by hamdiwanis** [comment]
@henrychavez  , you can set the marking mode in package.json file inside app folder, like this
```
{
  "android": {
    "v8Flags": "--expose_gc",
    "markingMode": "none"
  },
  ....
}
```
and yes you should try to use setTimeout  in the callback function of the plugin's scan function if you are doing ui related stuff in it. :)

**Comment by henrychavez** [comment]
@hamdiwanis thanks for your help!

This solve my problem :D

**Comment by MuhammadTahir92** [comment]
@EddyVerbruggen

**Comment by MuhammadTahir92** [comment]
@EddyVerbruggen  this link is not working please check

**Comment by jciombalo** [comment]
Thanks@hamdiwanis 

Your tips helped to solve my problem

**Comment by digiteco** [comment]
@henrychavez 
> ```
> {
>   "android": {
>     "v8Flags": "--expose_gc",
>     "markingMode": "none"
>   },
>   ....
> }
> ```
> 
> and yes you should try to use setTimeout in the callback function of the plugin's scan function if you are doing ui related stuff in it. :)

Thank you, it worked.
