### ISSUE TITLE
Scan page doesn't close when I navigate to another page

### ISSUE THREAD

**Issue by aydot** [EddyVerbruggen/nativescript-barcodescanner#114]
After a successful barcode capture, i try to navigate to another page, but the scan layout doesn't close. I have the _continuousScanCallback_ declared like so:

`   continuousScanCallback(result) {
      barcodescanner.stop()
      frameModule.topmost().navigate({
        moduleName: 'views/ticket/ticket',
        context: {
          ticketId: {id: result.text},
        },
      })
    },`

I know it's getting to the ticket page because I am able to see the console log I put on pageLoad in the ticket.js. The scan layout just stays there, blocking the ticket view maybe?

**Comment by EddyVerbruggen** [comment]
Perhaps add a little timeout before navigating?

And why use continuous scanning if you only want one result?

**Comment by aydot** [comment]
I was going back and forth between the _then_ and _ continuousScanCallback_ to see which would navigate away
Neither callbacks work. I added the timeout too..

`then(function(result) {
    barcodescanner.stop()
    setTimeout(function() {
      frameModule.topmost().navigate({
        moduleName: 'views/ticket/ticket',
        context: {
          ticketId: {id: result.text},
        },
      })
    }, 3000)
  })`

**Comment by aydot** [comment]
I moved the scan() call out of the pageLoaded function, and I am now triggering the scan when I click a button. Doing this yields the expected page transition.
Thanks!
