### ISSUE TITLE
not able to do npm run setup

### ISSUE THREAD

**Issue by Jimhub214** [EddyVerbruggen/nativescript-barcodescanner#115]
Hi,
I'm new in angular and nativescript, so I followed the section "Want a quick demo?" of README.md
1)    git clone https://github.com/EddyVerbruggen/nativescript-barcodescanner barcodedemo
2)    cd barcodedemo
3)    npm run setup 
4)    npm run demo.android (or demo.ios / demo.ios.device)

for the step 3) I got the following error
...
missing script: setup
...

Where is the setup script?
I'm also not able to find the demo.android or demo.ios scripts, is the quick start description still up-to-day?

**Comment by nicolasambroise** [comment]
When I run the script "npm run setup" in the "barecodedemo" folder I have the error : 
` package.json. no such file ...`
When I run it into "barcodedemo/demo" I have the error 
`missing file : setup`

**Comment by EddyVerbruggen** [comment]
Those instructions were old, thx.
