### ISSUE TITLE
Do not beepOnScan when device sound is muted

### ISSUE THREAD

**Issue by renestalder** [EddyVerbruggen/nativescript-barcodescanner#118]
beepOnScan is quite nice and we're able to deactivate it via the option. It would also be great if it reacts to the system volume, only binary. If volume is completely muted, don't play the beep sound.

**Comment by EddyVerbruggen** [comment]
Wait, doesn’t that work? On which platform is that?

**Comment by renestalder** [comment]
At least it didn't for me on iOS 10.3.3.

**Comment by rowdyrabouw** [comment]
Weird! 

I'm using 2.7.1 also on iOS (10.3.2) and beep sound isn't played when I mute the phone with the switch or turn the volume down.

This is my config:
``
this.barcodeScanner.scan({
      reportDuplicates: false,
      cancelLabel: 'Cancel'
      showTorchButton: true,
      openSettingsIfPermissionWasPreviouslyDenied: true, 
      continuousScanCallback: function(result) { ... },
      closeCallback: function() { ... }
    });
``

**Comment by rowdyrabouw** [comment]
Didn't set beepOnScan to false BTW, just the default value true.

**Comment by renestalder** [comment]
Just verified again. "Ringer" switch on the side of the phone is on "mute" and volume is on mute and beep still there.

Testing on an iPhone 5, but not sure if this is relevant.

**Comment by renestalder** [comment]
Configuration I use:

```js
this.scanOptions = {
            formats: 'QR_CODE, CODE_128',
            // iOS only, default 'Close'
            cancelLabel: 'Show event',
            // Android only, default is 'Place a barcode inside the viewfinder rectangle to scan it.'
            message: 'Use the volume buttons for extra light',
            showFlipCameraButton: true,
            preferFrontCamera: false,
            showTorchButton: false,
            torchOn: true,
            resultDisplayDuration: 500,
            orientation: 'portrait',
            openSettingsIfPermissionWasPreviouslyDenied: true
        };
```

**Comment by rowdyrabouw** [comment]
Maybe? I only tested it on iPhone 6

**Comment by renestalder** [comment]
I will give feedback when I tested on other devices too.
