### ISSUE TITLE
Barcode scanner doesn't work

### ISSUE THREAD

**Issue by jdnichollsc** [EddyVerbruggen/nativescript-barcodescanner#120]
Hi @EddyVerbruggen,

Is possible to integrate the [react native camera](https://github.com/lwansbrough/react-native-camera/issues) logic with this plugin? or with a NativeScript plugin? Because the scanner of this plugin doesn't work:
![whatsapp image 2017-12-01 at 11 46 50](https://user-images.githubusercontent.com/2154886/33495454-8b44c408-d694-11e7-9976-ac0f336844da.jpeg)
![whatsapp image 2017-12-01 at 11 46 50 1](https://user-images.githubusercontent.com/2154886/33495498-ab04552e-d694-11e7-8283-e65d17ef0363.jpeg)

Thanks in advance, Nicholls

**Comment by EddyVerbruggen** [comment]
What kind of barcodes are those?

**Comment by jdnichollsc** [comment]
The type of these barcodes is `CODE_128`, thanks for the help Eddy!

**Comment by jdnichollsc** [comment]
But with the React Native camera the scanner works perfect, so maybe we can reuse that logic from the NativeScript side, but I don't know

**Comment by EddyVerbruggen** [comment]
I beg to differ that this is a valid Code 128.. or at least it's some variant. Can you try scanning this one?

<img width="233" alt="screen shot 2017-12-02 at 12 37 15" src="https://user-images.githubusercontent.com/1426370/33515041-8d067060-d75d-11e7-8e0d-98bcdfe39fc3.png">

It's the same value as yours, generate on this site and it scans correctly with this plugin: https://barcode.tec-it.com/en/Code128?data=451009630567

So what kind of barcode is yours exactly?

**Comment by jdnichollsc** [comment]
Ohh ok, let me try your code. About my codes, these are `Interleaved 2 of 5, Code 128-A, or Code 128-B symbologies`
Thanks Eddy!
