### ISSUE TITLE
Volume buttons crash the app

### ISSUE THREAD

**Issue by jdnichollsc** [EddyVerbruggen/nativescript-barcodescanner#121]
Hi @EddyVerbruggen,
I was testing in an iPad that doesn't have flash, and the volume buttons crash the app.
Can you validate if the device support flash to prevent that issue? Can I help you? :)

Thanks in advance 👍

**Comment by EddyVerbruggen** [comment]
Hi,

I've just released version 2.7.2 that's supposed to fix this issue. But since I only have an iPad *with* a flashlight (the latest Pro model) I can't confirm the fix.. so please report back.

Cheers,
Eddy

**Comment by jdnichollsc** [comment]
Wowww thanks a lot @EddyVerbruggen, let me check! 👍

**Comment by jdnichollsc** [comment]
Works perfect, thanks @EddyVerbruggen for the help! I owe you one!

**Comment by EddyVerbruggen** [comment]
Thx for reporting back your findings! 👍

**Comment by jdnichollsc** [comment]
Always! 👍
