### ISSUE TITLE
Unable to use dialog or progress on scan callback

### ISSUE THREAD

**Issue by saintush** [EddyVerbruggen/nativescript-barcodescanner#122]
barcodescanner.scan({
    formats: "QR_CODE",   // Pass in of you want to restrict scanning to certain types
    cancelLabel: "EXIT. Also, try the volume buttons!", // iOS only, default 'Close'
    cancelLabelBackgroundColor: "#333333", // iOS only, default '#000000' (black)
    message: "Use the volume buttons for extra light", // Android only, default is 'Place a barcode inside the viewfinder rectangle to scan it.'
    showFlipCameraButton: true,   // default false
    preferFrontCamera: false,     // default false
    showTorchButton: true,        // default false
    beepOnScan: true,             // Play or Suppress beep on scan (default true)
    torchOn: false,               // launch with the flashlight on (default false)
    resultDisplayDuration: 500,   // Android only, default 1500 (ms), set to 0 to disable echoing the scanned text
    orientation: "landscape",     // Android only, optionally lock the orientation to either "portrait" or "landscape"
    openSettingsIfPermissionWasPreviouslyDenied: true // On iOS you can send the user to the settings app if access was previously denied
  }).then(
      function(result) {
        console.log("Scan format: " + result.format);
        console.log("Scan text:   " + result.text);
        var options = {
                title: "success",
                message: result.format+"  "+result.text,
                okButtonText: "OK"
            };
            dialogs.alert(options).then(() => {
                console.log(" ..........");
            });
      },
      function(error) {
        console.log("No scan: " + error);
      }
  );

i want to show results of scan in a dialog box . but got error  android.view.WindowLeaked: Activity com.google.zxing.client.android.CaptureActivity has leaked window DecorView.

Please help

**Comment by jhoopmann** [comment]
Hey, 

got same problem, just modified module dismissViewControllerAnimatedCompletion calls 2nd param to callback for vc animation completion.

QRCodeReaderDelegateImpl.prototype.readerDidScanResultForType = function (reader, text, type) {
        var _this = this;
        var validResult = false;
        if (this._isContinuous) {
            if (!this._scannedArray) {
                this._scannedArray = Array();
            }
            var newResult = this._scannedArray.indexOf("[" + text + "][" + type + "]") === -1;
            if (newResult || this._reportDuplicates) {
                var now = new Date().getTime();
                if (now - this._lastScanResultTs < 1700) {
                    return;
                }
                this._lastScanResultTs = now;
                validResult = true;
                this._scannedArray.push("[" + text + "][" + type + "]");
                this._callback(reader, text, type);
            }
        }
        else {
            validResult = true;
            var app_2 = utils.ios.getter(UIApplication, UIApplication.sharedApplication);
            app_2.keyWindow.rootViewController.dismissViewControllerAnimatedCompletion(
                true,
                function() {
                    _this._callback(reader, text, type);
                }
            );
        }
        if (validResult && this._player) {
            this._player.play();
        }
    };

**Comment by saintush** [comment]
I resolved this issue using intent broadcast.
Thanks jhoopmann  for reply.
