### ISSUE TITLE
Styling the entire scanner activity

### ISSUE THREAD

**Issue by darkyelox** [EddyVerbruggen/nativescript-barcodescanner#126]
Hey you can offer us a way for customize the scanner activity in its totally? i want this:
- customize the animations or indicators for the scanner (instead of blinking dots i want, for example, a rectangular sight with custom colors, or maybe a translucent image )
- remove or customize the overlay rectangular indicator (show only the camera view and the ability to scan from any area in the camera view)
- the ability for show valid recognized or not QR codes in scan realtime (for example i want to recognize only some kind of qr code data, for example, only some qr containing some standard JSON structure and change the color of the scan indicators when the QR is not valid)
- custom controls with styles, icons and callbacks

**Comment by phatakrajan** [comment]
Also need facility to show ads, header during the customization

**Comment by EddyVerbruggen** [comment]
Use this: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/ML_KIT.md#barcode-scanning
