### ISSUE TITLE
Dialogs module stop working after calling scan function

### ISSUE THREAD

**Issue by palpa** [EddyVerbruggen/nativescript-barcodescanner#13]
Hi,

After calling scan function, the dialogs module stop working raising below error:

JS: display error:  Error: java.lang.NullPointerException
JS:     android.app.AlertDialog.resolveDialogTheme(AlertDialog.java:143)
JS:     android.app.AlertDialog$Builder.<init>(AlertDialog.java:360)
JS:     java.lang.reflect.Constructor.constructNative(Native Method)
JS:     java.lang.reflect.Constructor.newInstance(Constructor.java:423)
JS:     com.tns.Platform.createInstance(Platform.java:302)
JS:     com.tns.Platform.callJSMethodNative(Native Method)
JS:     com.tns.Platform.dispatchCallJSMethodNative(Platform.java:816)
JS:     com.tns.Platform.callJSMethod(Platform.java:715)
JS:     com.tns.Platform.callJSMethod(Platform.java:694)
JS:     com.tns.Platform.callJSMethod(Platform.java:684)
JS:     com.tns.gen.android.view.View_OnClickListener_ftns_modules_ui_button_button_l19_c42__.onClick(android.view.View$OnClickListener.java)
JS:     android.view.View.performClick(View.java:4496)
JS:     android.view.View$PerformClick.run(View.java:18603)
JS:     android.os.Handler.handleCallback(Handler.java:733)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:136)
JS:     android.app.ActivityThread.main(ActivityThread.java:5433)
JS:     java.lang.reflect.Method.invokeNative(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:515)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
JS:     dalvik.system.NativeStart.main(Native Method)

I figure it out that this is related to **appmodule.android.currentContext** is lost (undefined) after calling scan function. I fixed it using below workaround in my code:

const context = appmodule.android.currentContext
  vm.scan().then(() => {
    appmodule.android.currentContext = context;
  });

Where vm.scan returns the barcodescanner.scan() promise

Is anyone else facing the same issue?, I'm using below dependencies:
"nativescript-barcodescanner": "^1.2.1",
"tns-core-modules": "^1.7.1"

Thanks.

**Comment by sebawita** [comment]
I am experiencing the same issue.
I've tested my app with NativeScript 1.5 and it works fine, however with 1.7.1 the dialogs stop working after I launch the scanner.

**Comment by EddyVerbruggen** [comment]
Interestingly this doesn't happen on my Android 4.4 device, I'll test with 5.1 in a sec.

Are you using the demo app, or do I need to run any other code to reproduce this?

**Comment by EddyVerbruggen** [comment]
Oh, updated tns core modules from 1.6 to 1.7 makes the alert dialog no longer work.

**Comment by sebawita** [comment]
I can confirm that this solved my problem:

```
var appmodule = require("application");
const context = appmodule.android.currentContext
vm.scan().then(() => {
appmodule.android.currentContext = context;
});
```

**Comment by EddyVerbruggen** [comment]
Thanks. I should be able to fix that inside the plugin. The change in behaviour is caused by [this dialogs module change](https://github.com/NativeScript/NativeScript/commit/e5979577b3e26087194336956d3bcaf3586cc868#diff-3a16ffa4f47ae28eddd264a0f084743c). I could do the same in the plugin. Need to check backward compatibility though.

**Comment by EddyVerbruggen** [comment]
Please update to 1.2.2 and you'll no longer need to work around this issue yourself.

Thanks for reporting this, both!
