### ISSUE TITLE
Build Conflict with nativescript-plugin-firebase

### ISSUE THREAD

**Issue by ShawnPavel** [EddyVerbruggen/nativescript-barcodescanner#131]
When building an app that uses both the nativescript-barcodescanner plugin and the [nativescript-plugin-firebase](https://github.com/EddyVerbruggen/nativescript-plugin-firebase) plugin the build fails.

It is the same issue as seen in #130 (Duplicate entry for AztecDetectorResult.class)

I was able to resolve it by modifying the `include.gradle` for the firebase plugin like so:
```
compile "com.facebook.android:facebook-android-sdk:4.+"
```
to
```
compile ("com.facebook.android:facebook-android-sdk:4.+"){ exclude group: 'com.google.zxing' }
```

Is there any way we can make these plugins compatible with each other without manually changing the `include.gradle` before I build?

**Comment by EddyVerbruggen** [comment]
I'm going to fix this according to your excellent 👌🏻 suggestion here: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/615

**Comment by wilsonbradleyc** [comment]
This is still happening with version 3.2.2, and version 9.1.1 of nativescript-plugin-firebase.  Let me know what is needed to troubleshoot.
