### ISSUE TITLE
Recognition speed is a bit slow on some devices

### ISSUE THREAD

**Issue by shiv19** [EddyVerbruggen/nativescript-barcodescanner#132]
Issue reported by @zeeshan

Recognition speed is pretty fast on Samsung devices,
but on some devices, it is either slow or doesn't work at all.

The type of barcode we're trying to scan is CODE_128

One problematic phone, we changed the mode from portrait to landscape, it started working better and faster, but still not as good as on Samsung (it's not the phone issue as other barcode scanners in market work equally good across all these phones.)

**Comment by EddyVerbruggen** [comment]
Please add the barcode you're scanning so I can test this. Although I only have 1 non-Samsung device.

**Comment by zeesulehria** [comment]
@EddyVerbruggen 
Code39: 
https://barcodegenerator.seagullscientific.com/Content/Images/BarCodes/56174b8b-3cdb-452d-98ed-1a0157677a72.png

Code128: 
https://www.leadtools.com/images/barcodes/code128.png

You can also text barcodes on google images to see performance.

**Comment by EddyVerbruggen** [comment]
@zeesulehria yeah those work fine on my Samsung S8. So what *specific* devices do you have trouble with?

**Comment by zeesulehria** [comment]
@EddyVerbruggen its QMobile Z12 Pro, Android version 6.0
@shiv19 also tested on some phone where he found scanner to perform slower than ZXing android demo

**Comment by EddyVerbruggen** [comment]
OK, but I don't have that model so how do we proceed?

@shiv19 what model is "some phone". And what barcodes did you test?

**Comment by shiv19** [comment]
It was slow on my Samsung Galaxy J7, running Android 6.0.1,

And worked fine on my Samsung Galaxy Note 5, running Android 7.0

**Comment by zeesulehria** [comment]
@EddyVerbruggen - Considering the frequency of problem, if you can try on few different phones you might be able to find some phone on which scanner doesn't work or performs slower (it also works slower on some samsung devices, probably with android 6?).
I can also provide you logs from QMobile Z12 Pro if it helps to debug the issue.

**Comment by EddyVerbruggen** [comment]
At this point it's not clear if it's an Android 6 (and below?) issue, or a hardware issue, or both. I have 3 Android devices running Android 7 or 8 and it all works fine. So I hope others can comment here as well.

@zeesulehria I assume you're limiting scanning to only the type of barcode you want to be recognized?

**Comment by zeesulehria** [comment]
@EddyVerbruggen - I had a thing, sorry for late reply.
One of the SAMSUNG devices that works perfectly fine runs on Android 6.0.1. It shows its not Android version issue. Also, ZXing demo app works perfectly fine on same device hardware on which this plugin shows issue.
@shiv19  mentioned this plugin is based on older ZXing version, so I have a feeling it might be the issue.  Alternatively, it can be some bug in plugin logic manifesting in some devices.

On how to proceed further, person debugging the problem must have a device on which this plugin shows issues. Perhaps, @EddyVerbruggen  can try to find such phone, or @shiv19 already have a phone which shows the issues. Once the right person to debug the issues has the phone, it would be way to proceed further. May be we should consider ZXing version upgrade if that can be an issue.

**Comment by EddyVerbruggen** [comment]
It could also be one of the modifications I had to add in the past to this plugin. Like you said, it’s impossible to tackle this without a problematic device.

**Comment by zeesulehria** [comment]
@EddyVerbruggen - If you are not able to arrange a device like Samsung Galaxy J7 [2015 edition] (which @shiv19 outlined as problematic), perhaps I can ship you the phone QMobile Z12 Pro, on which it has more severe problem?

**Comment by zeesulehria** [comment]
@EddyVerbruggen - Can I go past that modification in plugin you mentioned, to check if that change caused the issue?

**Comment by EddyVerbruggen** [comment]
That would mean you'd have to remove a bunch of code from the library. Pretty hard job. Perhaps it's easiest to just replace the modified lib with the latest jar that can be downloaded ([instructions](https://github.com/zxing/zxing/wiki/Getting-Started-Developing)). And if that works, add anything missing to that.

**Comment by zeesulehria** [comment]
@EddyVerbruggen - Ok I and @shiv19 will try out your suggestion, and let you know.

**Comment by zeesulehria** [comment]
@EddyVerbruggen - We are thinking to try an older version of plugin which doesn't have potentially problematic changes you suspect might have caused issue. 
Which plugin version would you recommend to try out?

**Comment by EddyVerbruggen** [comment]
To start with, 1.3.1 and 1.4.0 would be good candidates.

**Comment by juliancesar** [comment]
@zeesulehria, did you get performance improvements with this downgrades?

**Comment by zeesulehria** [comment]
@juliancesar - I couldn't get this done and had to postpone. If you are able to try it out, let me know. This would be good to try out.

**Comment by EddyVerbruggen** [comment]
For anyone not satisfied with the performance of this plugin for your usecase, please try [ML Kit in nativescript-plugin-firebase](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/ML_KIT.md#barcode-scanning).

It's a completely different implementation and IMO very fast. Also, you can embed the scanner UI on your page (doesn't need to be fullscreen), allowing you to add your own UI elements on top of the scanner view.
