### ISSUE TITLE
Allow embedding the scanner in a page

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/nativescript-barcodescanner#136]
Let's see if we can do something like this:

```xml
  <Barcode:BarcodeScannerView
      class="scanner-round"
      formats="QR_CODE, EAN_13"
      beepOnScan="true"
      reportDuplicates="true"
      preferFrontCamera="false"
      scanResult="onScanResult" />
```

.. which can be placed anywhere on the page, in any size.

I think on iOS it can be done, but Android may be a bit trickier because of the framework used.

**Comment by EddyVerbruggen** [comment]
Yeah, the used Android lib doesn't allow embedding (as fi. a fragment) inside a larger activity; it uses intents, so I'm limiting this feature to iOS only. See the readme, available in 2.7.5.

**Comment by Burgov** [comment]
I guess this half fixes https://github.com/EddyVerbruggen/nativescript-barcodescanner/issues/105. Is there any chance that we'll see it fixed for the other half (Android) as well, or is it simply not possible?

**Comment by EddyVerbruggen** [comment]
See my previous comment.

The only way would be using an entirely different framework on Android and that's not something I'd like to do in the short term.

**Comment by mrdegger** [comment]
maybe this could help? 
https://github.com/journeyapps/zxing-android-embedded

**Comment by EddyVerbruggen** [comment]
Alternative: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/ML_KIT.md#barcode-scanning
