### ISSUE TITLE
(android) embed barcode scanner in a tabview

### ISSUE THREAD

**Issue by marcocasadio** [EddyVerbruggen/nativescript-barcodescanner#139]
Hi,
I've embedded the barcode scanner into a TabView, this is the code:
`        <BarcodeScanner
            class="bar-code-scanner"
            formats="CODE_39"
            beepOnScan="true"
            reportDuplicates="false"
            preferFrontCamera="false"
            (scanResult)="onScanResult($event)">
        </BarcodeScanner>`

on iOS it works correctly but on Android I get this:
`JS: ERROR TypeError: viewClass is not a constructor
JS: ERROR CONTEXT [object Object]`

I don't know how to fix this. I need that the camera for scan is always active (embed) and don't open with a tap on a button.

thanks

**Comment by EddyVerbruggen** [comment]
Embedding is iOS only, so wrap that in an `*ngIf` or `<ios>`, and launch the scanner on Android from code.

**Comment by EddyVerbruggen** [comment]
UPDATE: You can now use the Firebase plugin to embed a Machine Learning - powered barcode scanner. See https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/ML_KIT.md#barcode-scanning
