### ISSUE TITLE
Is it possible to use on an emulator? 

### ISSUE THREAD

**Issue by geoffbullen** [EddyVerbruggen/nativescript-barcodescanner#140]
Question, not bug:

Is it possible to use an image of a barcode when running on a device emulator?

**Comment by rowdyrabouw** [comment]
No, you have to do some coding yourself like this for the iOS emulator
```
if (config.debug) {
// use contents of barcode
}
else {
// use scanner
}
```

For Android you can use the GenyMotion emulator.
You can hook that up to your laptops webcam.
