### ISSUE TITLE
trouble implementing in nativescript-angular

### ISSUE THREAD

**Issue by r0zar** [EddyVerbruggen/nativescript-barcodescanner#141]
Seeing some errors when following the getting starting guide:
```
JS: ERROR Error: Uncaught (in promise): Error: Template parse errors:
JS: Only void and foreign elements can be self closed "BarcodeScanner" ("
JS:     -->
JS:     <GridLayout class="page page-content" tkMainContent>
JS:         [ERROR ->]<BarcodeScanner
JS:           class="scanner-round"
JS:           formats="QR_CODE, EAN_13"
JS: "): ng:///data/data/org.nativescript.KipoTrac/files/app/home/home.component.html@31:8
```

When i remove the self-closing tag i get a different error:
```
JS: ERROR Error: Uncaught (in promise): TypeError: viewClass is not a constructor
JS: TypeError: viewClass is not a constructor
```

I'm a bit lost.

**Comment by r0zar** [comment]
I am able to inject the scanner into my component:
```
JS: === dump(): dumping members ===
JS: {
JS:     "broadcastManager": null,
JS:     "uniquelyScannedCodes": []
JS: }
JS: === dump(): dumping function and properties names ===
JS: wasCameraPermissionGranted()
JS: requestCameraPermissionInternal()
JS: available()
JS: hasCameraPermission()
JS: requestCameraPermission()
JS: stop()
JS: scan()
JS: === dump(): finished ===
JS: Available? true
```

**Comment by r0zar** [comment]
It seems like the problem is the `<BarcodeScanner>` is not recognized.

**Comment by r0zar** [comment]
I get the following error when i try to run `this.barcodeScanner.requestCameraPermission()`

```
JS: Error in barcodescanner.requestCameraPermission: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.requestPermissions(java.lang.String[], int)' on a null object reference
```

**Comment by DillonStreator** [comment]
I am seeing the same issue with regards to the `viewClass is not a constructor`
I've followed the getting started guide as well as following a tutorial here:
https://www.techiediaries.com/nativescript-barcode-qr-code-scanner-angular/

**Comment by ndcunningham** [comment]
I think the view class is only implemented for IOS and not available in Android
As you can see here it exports class: https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/master/src/barcodescanner.android.ts#L13

While on IOS it exports https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/master/src/barcodescanner.ios.ts#L5 and https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/master/src/barcodescanner.ios.ts#L63

**Comment by EddyVerbruggen** [comment]
Embedding the view is for iOS only, so make sure that doesn't run on Android like this for XML-based layouts:

https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/faaa443417dc3cf3698952eacdd49f634b69cd6a/demo/app/main-page.xml#L17-L31

Or add an `*ngIf` for Angular apps.

Does that help?

**Comment by EddyVerbruggen** [comment]
I've now added an Angular demo to the repo.

**Comment by gdurand** [comment]
I've stumbled upon this issue too. I think you should clearly indicate that the embedded view is for iOS only.
BTW the demo-ng does not work for Android, so perhaps you should adapt it to support it. This way it'll be even more clear how to manage both platforms.

**Comment by EddyVerbruggen** [comment]
@gdurand I should do this and I should do that. You should do a PR if you're not happy with my work.

**Comment by steinerj** [comment]
Look at: https://github.com/EddyVerbruggen/nativescript-barcodescanner/pull/154

**Comment by mokth** [comment]
for android u need to invoke the scanner from code.

    public onScan(){
      this.barcodeScanner.scan({
              formats: "QR_CODE, EAN_13",
              cancelLabel: "EXIT. Also, try the volume buttons!", // iOS only, default 'Close'
              cancelLabelBackgroundColor: "#333333", // iOS only, default '#000000' (black)
              message: "Use the volume buttons for extra light", // Android only, default is 'Place a barcode inside the viewfinder rectangle to scan it.'
              showFlipCameraButton: true,   // default false
              preferFrontCamera: false,     // default false
              showTorchButton: true,        // default false
              beepOnScan: true,             // Play or Suppress beep on scan (default true)
              torchOn: false,               // launch with the flashlight on (default false)
              closeCallback: () => { console.log("Scanner closed")}, // invoked when the scanner was closed (success or abort)
              resultDisplayDuration: 500,   // Android only, default 1500 (ms), set to 0 to disable echoing the scanned text
            // orientation: orientation,     // Android only, default undefined (sensor-driven orientation), other options: portrait|landscape
              openSettingsIfPermissionWasPreviouslyDenied: true // On iOS you can send the user to the settings app if access was previously denied
      }).then((result) => {
        // Note that this Promise is never invoked when a 'continuousScanCallback' function is provided
         console.log(result);        
      }, (errorMessage) => {
        console.log("No scan. " + errorMessage);
        this.barcodeScanner.stop();
      }
    );
  }
