### ISSUE TITLE
Does this support Vuejs

### ISSUE THREAD

**Issue by WangHansen** [EddyVerbruggen/nativescript-barcodescanner#146]
Hi, first of all, thank you for the hard work. I wanted to know if this supports Vuejs, since in documents, there are sections dedicated to Angular, if so, does it work the same as in Angular, thanks.

**Comment by EddyVerbruggen** [comment]
It should work just fine, just like the example I gave here: https://nativescript-vue.org/en/docs/getting-started/nativescript-plugins/

**Comment by WangHansen** [comment]
I am not sure what I did wrong here, I used the [vue-cli-template](https://github.com/nativescript-vue/vue-cli-template) from nativescript-vue and it is not working. Here is my code:
    
    //main.js
    import Vue from 'nativescript-vue';
    import HelloWorld from './components/HelloWorld';
    import store from './store';
    import './styles.scss';
    Vue.registerElement("BarcodeScanner", () => require("nativescript-barcodescanner").BarcodeScannerView);
    new Vue({
      render: h => h(HelloWorld),
      store,
    }).$start();

And for UI

    //HelloWorld.vue
    ...
    <BarcodeScanner
      class="scanner-round"
      formats="QR_CODE"
      beepOnScan="true"
      preferFrontCamera="false"
      (scanResult)="onScanResult($event)">
    </BarcodeScanner>
    ...

This is not working 
>the error message:

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.application/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: n is not a constructor
File: "file:///data/data/org.nativescript.application/files/app/app.js, line: 1, column: 78635

StackTrace: 
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 91695
	Frame: function:'t.createElement', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 93094
	Frame: function:'an', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 27053
	Frame: function:'u', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 94419
	Frame: function:'m', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 95317
	Frame: function:'u', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 94443
	Frame: function:'m', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 95317
	Frame: function:'u', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 94443
	Frame: function:'e.nodeOps', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 99575
	Frame: function:'e._update', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 108676
	Frame: function:'r', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 16143
	Frame: function:'ms.get', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 78603
	Frame: function:'ms', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 78526
	Frame: function:'qe', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 16167
	Frame: function:'xl', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 118473
	Frame: function:'Qo.$mount', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 118770
	Frame: function:'init', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 105772
	Frame: function:'l', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 94713
	Frame: function:'u', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 94148
	Frame: function:'e.nodeOps', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 100061
	Frame: function:'e._update', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 108676
	Frame: function:'r', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 16143
	Frame: function:'ms.get', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 78603
	Frame: function:'ms', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 78526
	Frame: function:'qe', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 16167
	Frame: function:'create', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 118325
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 51, column: 22
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 101, column: 16
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: n is not a constructor
File: "file:///data/data/org.nativescript.application/files/app/app.js, line: 1, column: 78635

StackTrace: 
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 91695
	Frame: function:'t.createElement', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 93094
	Frame: function:'an', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 27053
	Frame: function:'u', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 94419
	Frame: function:'m', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 95317
	Frame: function:'u', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 94443
	Frame: function:'m', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 95317
	Frame: function:'u', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 94443
	Frame: function:'e.nodeOps', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 99575
	Frame: function:'e._update', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 108676
	Frame: function:'r', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 16143
	Frame: function:'ms.get', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 78603
	Frame: function:'ms', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 78526
	Frame: function:'qe', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 16167
	Frame: function:'xl', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 118473
	Frame: function:'Qo.$mount', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 118770
	Frame: function:'init', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 105772
	Frame: function:'l', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 94713
	Frame: function:'u', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 94148
	Frame: function:'e.nodeOps', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 100061
	Frame: function:'e._update', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 108676
	Frame: function:'r', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 16143
	Frame: function:'ms.get', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 78603
	Frame: function:'ms', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 78526
	Frame: function:'qe', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 16167
	Frame: function:'create', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 118325
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 51, column: 22
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 101, column: 16
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
	at android.app.Activity.performCreate(Activity.java:6679)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
	... 9 more

Could you please possibly write a quick demo for vue, thanks

**Comment by EddyVerbruggen** [comment]
Try it on iOS instead and you'll see it works; the embedded scanner is iOS only.
