### ISSUE TITLE
App freezes/delays (~4000ms) after barcodescanner closes

### ISSUE THREAD

**Issue by isaacfi** [EddyVerbruggen/nativescript-barcodescanner#148]
This issue was the #107 but it is closed. That's why I create this one.

I have the same issue. This is the example, you have to start to scan and you can cancel or scan the barcode, then press constantly the "Get Delay" button to get the time in milliseconds. The delay is about 3 seconds.

[barcodeTest.zip](https://github.com/EddyVerbruggen/nativescript-barcodescanner/files/1949382/barcodeTest.zip)

Regards

**Comment by EddyVerbruggen** [comment]
Did you try adding `resultDisplayDuration: 0`? Not much beyond that to make it snappier.

**Comment by isaacfi** [comment]
Yes, and it is not working. this is the delay at the project that I shared you:
![screenshot_2018-04-27-07-53-49-510_org nativescript barcodetest](https://user-images.githubusercontent.com/647070/39363542-4e808b86-49f0-11e8-8f95-811bb12a0441.png)

**Comment by EddyVerbruggen** [comment]
I tested your project before my reply, and setting that property from default (as in your demo app) to `0` makes the reported "delay" drop from ~4 to ~2 seconds on my Samsung, and from a user perspective I don't really notice it because the screen transition from scanner to app is also part of those ~2 seconds.

**Comment by s-doddapaneni** [comment]
I have the same issue. I added resultDisplayDuration: 0. But the delay is after the screen transition from scanner to app. If you press back button or scan a barcode, then there is delay.
Is there any solution for this?
