### ISSUE TITLE
Cannot build in cloud

### ISSUE THREAD

**Issue by teobugslayer** [EddyVerbruggen/nativescript-barcodescanner#149]
Hey Eddy,

the source code has ```DEVELOPMENT_TEAM``` committed as seen [here](https://github.com/EddyVerbruggen/nativescript-barcodescanner/search?utf8=✓&q=DEVELOPMENT_TEAM+%3D+8Q5F6M3TNS&type=_). This prevents the cloud builds inside Sidekick from successfully building the demo app. Can you fix this issue, please?

**Comment by EddyVerbruggen** [comment]
Hi! I can't guarantee this won't happen again, but I'll remove it for now. Do you need a new npm release as well?

Cheers,
Eddy
