### ISSUE TITLE
Failed to build plugin nativescript-barcodescanner :

### ISSUE THREAD

**Issue by divyachandana** [EddyVerbruggen/nativescript-barcodescanner#150]
Failed to build plugin nativescript-barcodescanner :
Error: Command failed: gradlew.bat -p B:\main projects\srs\client\srs\platforms\tempPlugin\nativescript_barcodescanner assembleRelease -PcompileSdk=android-27 -PbuildToolsVersion=27.0.3 -PsupportVersion=26.0.0-alpha1

FAILURE: Build failed with an exception.

* What went wrong:
Task 'projects\srs\client\srs\platforms\tempPlugin\nativescript_barcodescanner' not found in root project 'main'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by ArielSlimming** [comment]
????

**Comment by ArielSlimming** [comment]
i have some problem

**Comment by divyachandana** [comment]
delete `platforms` folder and try to `build`. Issue solved somehow.
