### ISSUE TITLE
Is it possible to use the scanner with natiscriptvue?

### ISSUE THREAD

**Issue by Andrs81** [EddyVerbruggen/nativescript-barcodescanner#151]
Thanks for the help, I have this question, I have been trying to use the scanner with nativescript-vue with this format:

<BarcodeScanner
              class="scanner-round"
              formats="QR_CODE, EAN_13"
              beepOnScan="true"
              reportDuplicates="true"
              preferFrontCamera="false"
              (scanResult)="onScanResult($event)">
        </BarcodeScanner>

**It doesn't let me see the camera and I get no error when I have that added. so, I remove that and then I try to use the scan this way:**

<Button @tap="onScan" text="Scan QR" class="btn btn-outline"/>
 
**Calling this method:**

onScan() {
      barcodescanner
        .scan({
          formats: "QR_CODE,PDF_417", // Pass in of you want to restrict scanning to certain types
          message: "Use the volume buttons for extra light", // Android only, default is 'Place a barcode inside the viewfinder rectangle to scan it.'
          showFlipCameraButton: true, // default false
          preferFrontCamera: false, // default false
          showTorchButton: true, // default false
          beepOnScan: true, // Play or Suppress beep on scan (default true)
          torchOn: false, // launch with the flashlight on (default false)
          closeCallback: function() {
            console.log("Scanner closed");
          }, // invoked when the scanner was closed (success or abort)
          resultDisplayDuration: 500, // Android only, default 1500 (ms), set to 0 to disable echoing the scanned text
          orientation: "landscape", // Android only, optionally lock the orientation to either "portrait" or "landscape"
          openSettingsIfPermissionWasPreviouslyDenied: true // On iOS you can send the user to the settings app if access was previously denied
        })
        .then(
          function(result) {
            alert(result)
            console.log("Scan format: " + result.format);
            console.log("Scan text:   " + result.text);
          },
          function(error) {
            console.log("No scan-: " + error);
          }
        )

I get  'No scan-: TypeError: Cannot read property \'zxing\' of undefined'

**Comment by EddyVerbruggen** [comment]
Sounds like the native aar from the plugin hasn't been added to your platforms/android folder. Either remove the platforms/android folder and build again, or your project setup doesn't correctly copy the plugin dependencies.

**Comment by ahhatem** [comment]
#152   I have just managed to make it work. I don't know if that is a bug or what but the change I have done made it work on my setup.

**Comment by Andrs81** [comment]
thanks for the help. As tns is not yet working with nativescript-vue I was using npm run. So, what I did was I  removed the platforms/android folder and I ran npm run clean and then build again and it worked.
