### ISSUE TITLE
demo-ng not showing scanner

### ISSUE THREAD

**Issue by Brandon2255p** [EddyVerbruggen/nativescript-barcodescanner#153]
Hi I have been trying to use this library in my nativescript ng app but have had no success.

Is the demo-ng app supposed to be working? I compiled and ran it - no scanner appears :(

I am confused about the implementation - the readme.md seems to suggest a few different ways of doing it but its not clear what the differences are.

I want to have a continuous scanner until a code is found.

**Comment by EddyVerbruggen** [comment]
Which device (not emulator) do you use to these the demo-ng app?

**Comment by Brandon2255p** [comment]
I used an Android Xiaomi Redmi 2 with Lineage OS 7.1 Android Nougat

Only the list of items appears.

**Comment by EddyVerbruggen** [comment]
Is it device specific?

**Comment by Brandon2255p** [comment]
I don't have an iPhone so can only test android. I will try it on other devices. But the fact that no UI element appears on the emulator or my device gives me very little hope

**Comment by steinerj** [comment]
I think you might be looking at the iOS only sample...
Check out: https://github.com/EddyVerbruggen/nativescript-barcodescanner/pull/154
