### ISSUE TITLE
Vue - Stopping barcode scanner when modal dismissed

### ISSUE THREAD

**Issue by absolutehype** [EddyVerbruggen/nativescript-barcodescanner#157]
I have a modal with a barcode scanner inside, when the modal is closed the barcode scanner continues to scan in the background. I would have expected the scanner to have been disposed of, so now i'm trying to call stop on the scanner instance using the code below to no avail.

I know this is a bit of a Vue oriented question, but how do I call close on the scanner when it's embedded in my template and i'm not programatically creating an instance? I'm getting `this.$refs.BarcodeScanner.nativeView.stop is not a function.`

```vue
<template>
    <Page class="scan">
        <BarcodeScanner
            width="100%"
            height="100%"
            ref="BarcodeScanner"
            formats="QR_CODE, CODE_128, CODE_39, EAN_13"
            beepOnScan="true"
            reportDuplicates="true"
            preferFrontCamera="false"
            @scanResult="scanResult">
        </BarcodeScanner>
    </Page>
</template>

<script>
import { mapActions } from 'vuex';

export default {

    methods: {
        ...mapActions({
            addTask: 'tasks/add'
        }),
        scanResult(result) {
            console.log(`Format: ${ result.format }, Value: ${ result.text }`);
            this.addTask({ barcode: result.text, format: result.format });
            this.close()
        },
        close() {
            this.$refs.BarcodeScanner.nativeView.stop();
            this.$modal.close();
        }
    }
}
</script>

<style>
</style>
```

**Comment by EddyVerbruggen** [comment]
Indeed, this is a Vue question rather than a plugin question.

My 2 cents anyway: is `close()` called when the modal hides? (make sure by adding a `console.log`. If so, in case `this.$refs.BarcodeScanner` is a hting, does changing `this.$refs.BarcodeScanner.nativeView.stop();` to `this.$refs.BarcodeScanner.stop();` make it work?

**Comment by absolutehype** [comment]
@EddyVerbruggen the close callback on the BarcodeScanner does not fire when the modal is closed. Digging further into this issue i noticed that nothing in the view is disposed of when the modal is closed. This may not be an issue with this plugin but a lifecycle issue within nativescript/nativescript-vue. I've raised an issue https://github.com/nativescript-vue/nativescript-vue/issues/248
