### ISSUE TITLE
Using scanning a barcode breaks dialogs on Android

### ISSUE THREAD

**Issue by NathanaelA** [EddyVerbruggen/nativescript-barcodescanner#16]
I know this is a weird issue; but basically if you create one button to scan and another button to pop up say Dialogs.prompt.   After you scan, if you do the button to bring up the prompt you will see the following callstack:
```
 Dialog err Error: java.lang.NullPointerException
    android.app.AlertDialog.resolveDialogTheme(AlertDialog.java:143)
    android.app.AlertDialog$Builder.<init>(AlertDialog.java:360)
    java.lang.reflect.Constructor.constructNative(Native Method)
    java.lang.reflect.Constructor.newInstance(Constructor.java:423)
...
```
I'm not sure what the Zxing or the wrapper does, but it somehow looks like it messes up the theme.

This is using Android runtimes 1.7x with common core 1.7.x

Example Code for each button:
```
   BarcodeScanner.scan({ showFlipCameraButton: true })
      .then(  function(result) {  console.log("result", result);  })
      .catch(function(err) { console.log("ScanErr:", err); });

  Dialogs.prompt("Please type it in", "")
       .then(function (result) { console.log("result", result); })
      .catch(function (err) { console.log("Dialog err", err);  });
```

**Comment by EddyVerbruggen** [comment]
Did you see #13 and #14?

**Comment by NathanaelA** [comment]
Oy, now I feel silly.   I missed the closed issues -- I looked in the open issues.

**Comment by EddyVerbruggen** [comment]
No worries, thanks for your detailed bugreport and reproductionpath, they would have been very helpful if I had not already solved it.
