### ISSUE TITLE
Integration with nativescript-vue

### ISSUE THREAD

**Issue by yoann54** [EddyVerbruggen/nativescript-barcodescanner#160]
Hello, I'm having hard time to integrate this plugin with nativescript vue, does anyone have a link with a little example ?

for now im doing like that and it return me an error like so : System.err: ReferenceError: BarcodeScanner is not defined
System.err: File: "<unknown>, line: 1, column: 265

`<template>
  <Page class="page">
    <ActionBar class="action-bar" title="Home"/>

    <StackLayout>
              <Button class="btn btn-primary" @tap="scan">Scan a product</Button>
    </StackLayout>

  </Page>
</template>`

`<script>
import BarcodeScanner from "nativescript-barcodescanner";

export default {
  data() {
    return {
      barcodescanner: new BarcodeScanner()
    };
  },
  methods: {
    scan: function() {
      this.barcodescanner
        .scan({
          formats: "QR_CODE,PDF_417", 
          cancelLabel: "EXIT. Also, try the volume buttons!", 
          cancelLabelBackgroundColor: "#333333",
          message: "Use the volume buttons for extra light",  inside the viewfinder rectangle to scan it.'
          showFlipCameraButton: true,
          preferFrontCamera: false,
          showTorchButton: true,
          beepOnScan: true, 
          torchOn: false, // launch with the flashlight on (default false)
          closeCallback: function() {
            console.log("Scanner closed");
          }, // invoked when the scanner was closed (success or abort)
          resultDisplayDuration: 500, 
          orientation: "landscape",
          openSettingsIfPermissionWasPreviouslyDenied: true
        })
        .then(
          function(result) {
            console.log("Scan format: " + result.format);
            console.log("Scan text:   " + result.text);
          },
          function(error) {
            console.log("No scan: " + error);
          }
        );
    }
  }
};
</script>`

I also tried to import it from main.js but i have the same problem System.err: "ReferenceError: BarcodeScanner is not defined
System.err: File: "<unknown>, line: 1, column: 265"

**Comment by carlosmojopicon** [comment]
I think you should import the library this way:
`import {BarcodeScanner} from "nativescript-barcodescanner";`

**Comment by yoann54** [comment]
Indded this way it works fine thx for ur help.

Le dim. 29 juil. 2018 à 22:10, carlosmojopicon <notifications@github.com> a
écrit :
