### ISSUE TITLE
 No scan. TypeError: Cannot read property 'client' of undefined

### ISSUE THREAD

**Issue by ann1111** [EddyVerbruggen/nativescript-barcodescanner#165]
HI @EddyVerbruggen ,

When ever I try to tab on scan it shows this error

https://play.nativescript.org/?template=play-ng&id=03Ge8E&v=5

**Comment by stephen1977** [comment]
i was getting this too. this is what worked for me, good luck
Delete the app from your device
Remove the folder platforms/android. This triggers a complete rebuild
run tns run android

**Comment by lospringliu** [comment]
Got the same with Nativescript-vue, the request permission did not bring up any page

**Comment by lospringliu** [comment]
Actually worked when run on the device. Using tns preview --bundle does not work though

**Comment by EddyVerbruggen** [comment]
I don't think the 'preview' app ships with this plugin, let alone the latest version.

**Comment by chethanhatwar** [comment]
i am getting same error too.
this is what i tried 
Remove the folder platforms/android.
run tns run android
Still same issue.. couldn't able to resolve this. Please help..

**Comment by chrajkumar** [comment]
i am getting same error too.
this is what i tried
Remove the folder platforms/android.
run tns run android
Still same issue.. couldn't able to resolve this. Please help..

**Comment by wildwillyd** [comment]
Just had this same issue with my app build, needless to say I was pretty lost after this goose chase in here but here's how I fixed it.

MAKE SURE you have the command $ tns plugin add nativescript-barcodescanner and run this in your app directory. I dont think just the $ npm install nativescript-barcodescanner is sufficient.  
Also create a new virtual device and make sure NPM is updated fully. This should hopefully resolve any issues.

**Comment by EddyVerbruggen** [comment]
Yep. See https://github.com/EddyVerbruggen/nativescript-barcodescanner#installation
