### ISSUE TITLE
demo-ng error while move to scanner page on android devices

### ISSUE THREAD

**Issue by shamoh19** [EddyVerbruggen/nativescript-barcodescanner#168]
Using NS version: 5.0.0

While navigating to scanner page on demo-ng project facing below error
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: ERROR Error: Uncaught (in promise): TypeError: viewClass is not a constructor
JS: TypeError: viewClass is not a constructor
JS:     at ViewUtil.createView (file:///data/data/org.nativescript.demong/files/app/tns_modules/nativescript-angular/view-util.js:202:20)
JS:     at NativeScriptRenderer.createElement (file:///data/data/org.nativescript.demong/files/app/tns_modules/nativescript-angular/renderer.js:108:30)
JS:     at DebugRenderer2.createElement (file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js:15245:49)
JS:     at createElement (file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js:10618:27)
JS:     at createViewNodes (file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js:13783:61)
JS:     at callViewAction (file:///data/data/org.nativescript.demong/files/app/tns_modules/@angular/core/bundles/core.umd.js:14256:13)

**Comment by EddyVerbruggen** [comment]
Hi, I've just bumped the dependencies in `demo-ng` to NativeScript 5 and ran it on my iOS device without problems.

So update, then remove the demo-ng/platforms folder and run `npm run demo-ng` again.

**Comment by shamoh19** [comment]
IOS its working super fine. Still facing same error ("**TypeError: viewClass is not a constructor**") in Android

**Comment by shamoh19** [comment]
IOS its working super fine. Still facing same error ("**TypeError: viewClass is not a constructor**") in Android

**Comment by EddyVerbruggen** [comment]
Embedding the scanner is not supported on Android.
