### ISSUE TITLE
PDF417 support for android is not working

### ISSUE THREAD

**Issue by carvarr** [EddyVerbruggen/nativescript-barcodescanner#17]
Hello

I updated my project using this awsome module but actually I can't read PDF417 barcodes in android, I'm using my xperia z3 for testing, do I need some additional configuration ?

Version: 1.3.1

Thanks

**Comment by EddyVerbruggen** [comment]
Do any of the answers to [these issues](https://github.com/zxing/zxing/search?q=pdf417&type=Issues&utf8=%E2%9C%93) help? It's the library that this project uses underneath for Android. Perhaps [this one](https://github.com/zxing/zxing/issues/427).

**Comment by EddyVerbruggen** [comment]
That being said [I don't think PDF417 is supported by default](https://github.com/zxing/zxing/blob/b189fd1d5629770b1ecbdf3e2f55a37776538957/android/src/com/google/zxing/client/android/DecodeThread.java#L83). I may need to add a way for developers to be able to pass in a `formats` array to specify what should be scanned. That would also help speeding up scanning in case you're only interested in one or two types of barcode for your app.

**Comment by EddyVerbruggen** [comment]
Check out 1.3.2: you can now pass in `formats` to also enable `PDF_417`.
