### ISSUE TITLE
demo-ng broken from Jun 14th commit

### ISSUE THREAD

**Issue by thesminc** [EddyVerbruggen/nativescript-barcodescanner#171]
I believe that this commit https://github.com/EddyVerbruggen/nativescript-barcodescanner/commit/d61c4333e4162e99df8b24f434d059ecf6bedc01  on Jun 14 broke the work done on the Angular portion of this repo in demo-ng (https://github.com/EddyVerbruggen/nativescript-barcodescanner/commit/1b4f6a2f0122ba2972dddfa8b15800f4900e0423) . After rolling back the demo-ng works and new errors that are being reported by @shamoh19 https://github.com/EddyVerbruggen/nativescript-barcodescanner/issues/168 are resolved.

**Comment by EddyVerbruggen** [comment]
Just tested demo-ng on iOS and it ran fine.
