### ISSUE TITLE
How to get a reference from embedded iOS scanner

### ISSUE THREAD

**Issue by karo-dc** [EddyVerbruggen/nativescript-barcodescanner#172]
I don't want to switch to another screen when I tap 'Scan' button.
When a page mounts the scanner opens automatically when I use embedded scanner for iOS. It's good. No new pages are being opened The entire camera view opens up inside my page where I have other elements, and all my elements partially mask the camera view: and that's also fine for me. But I also want to get reference of scanner which I want to stop after scanning QR, because it's scanning infinitely (I think the scanner  does not terminate and the camera is always working under the hood).

**Comment by EddyVerbruggen** [comment]
Navigating back from that screen would destroy it, but if you want to stay on the screen you may need to call `disposeNativeView` on [evt.object](https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/9680908810bfa8e7f3ec9037b6d0efe312c0efd0/demo-ng/app/item/item-detail.component.ts#L28). I didn't try it, but perhaps it's a step in the right direction for your usecase.

**Comment by karo-dc** [comment]
@EddyVerbruggen ok, thanks for response, will check after tell you

**Comment by PathonHauser** [comment]
@EddyVerbruggen @karo-dc  Did you guys solve this? Looking for the same thing...

**Comment by karo-dc** [comment]
@PathonHauser I'am using firebase Ml Kit scanner for this
