### ISSUE TITLE
UPC_A support on iOS?

### ISSUE THREAD

**Issue by timdmackey** [EddyVerbruggen/nativescript-barcodescanner#176]
With the demo app, even though the app is set to scan EAN_13 codes, it still scans UPC_A codes and just adds a zero to the beginning of them. In fact, this isn't surprising given that EAN_13 is a superset of UPC_A, and 12-digit UPC_A codes can be converted to an equivalent EAN_13 code by prepending a zero to the code.

This leads me to wonder, why is it that UPC_A codes aren't supported on iOS? What is preventing it? Is it possible to add support? Or should I be using EAN_13 for both, and treating all UPC_A codes as EAN_13?

**Comment by EddyVerbruggen** [comment]
I think it actually does support UPC_A because of what you mentioned. So with EAN_13 enabled you can also scan UPC_A, according to this: https://developer.apple.com/documentation/avfoundation/avmetadataobjecttypeean13code?language=objc

Do you think updating the readme would suffice?

**Comment by timdmackey** [comment]
Good point, thanks for the link to Apple’s docs. I also found this page that explicitly states the behavior of adding a leading zero: https://developer.apple.com/library/archive/technotes/tn2325/_index.html#//apple_ref/doc/uid/DTS40013824-CH1-IS_UPC_A_SUPPORTED

I think how to proceed may depend on how Android behaves when using the UPC_A flag. If Android returns a 12-digit code, the inconsistency would be problematic if developers aren’t aware that they’ll need to normalize the codes before using the data.

**Comment by timdmackey** [comment]
If Android does return a 12-digit code, it looks like it’s pretty straightforward to normalize this. As noted here, EAN-13 codes with a leading zero are by definition a UPC-A code, so all you need to do is either add or remove the leading zero depending on which way you’re converting: https://stackoverflow.com/questions/22767584/ios7-barcode-scanner-api-adds-a-zero-to-upca-barcode-format

**Comment by EddyVerbruggen** [comment]
Interesting findings, thanks. I'm personally not interested in UPC-A so don't hold your breath for me doing this any time soon, but I'll flag it as 'help wanted' and perhaps on a rainy day I can take a stab at it myself.

**Comment by timdmackey** [comment]
Fair enough, thanks for your feedback!

**Comment by timdmackey** [comment]
Ooh, fantastic! Thanks for doing this.

**Comment by timdmackey** [comment]
With this change, I suggest also making a note in the documentation that you **cannot use both** UPC_A and EAN_13 at the same time, that you **must** choose one or the other.

**Comment by EddyVerbruggen** [comment]
@timdmackey Thanks for the great assistance!

I actually intended to check the formats the develop passed in but forgot about it, so thanks!

The best way to be consistent with Android is reporting UPC_A when a leading `0` is detected and either no formats have been requested ("scan everything") or `UPC_A` has been requested explicitly. If you also specify `EAN_13` then still the `0`will be stripped when the plugin thinks it's actually `UPC_A`. Again, that's how Android behaves as well.

Note that this no longer is a "breaking change" so bumping to 2.8.0 will suffice. Only users who don't pass in formats (not recommended anyway) may now get an "EAN_13" reported as UPC_A, with one less `0`. Not a biggie IMO.

**Comment by timdmackey** [comment]
> The best way to be consistent with Android is reporting UPC_A when a leading 0 is detected and either no formats have been requested ("scan everything") or UPC_A has been requested explicitly.
That sounds good
> If you also specify `EAN_13` then still the 0 will be stripped when the plugin thinks it's actually UPC_A. Again, that's how Android behaves as well.
Do you mean if the developer specifies `EAN_13` and not `UPC_A` that the zero will still be stripped? I'm surprised that's what Android does, but if so it's important to keep things consistent between iOS and Android if you're going to have this feature.

**Comment by EddyVerbruggen** [comment]
Argh! To complicate things, I just found out that on Android, when specifying formats as `EAN_13` it will still scan `UPC_A` and report it as `UPC_A`, with a stripped leading `0`. So that's actually what I had before my last commit. 🤔

**Comment by EddyVerbruggen** [comment]
I'm going to see what [ML Kit does](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/ML_KIT.md#barcode-scanning) under similar circumstances, and report back here.

**Comment by timdmackey** [comment]
Argh, that's frustrating. I wonder if having a special flag for it would be a solution? Something like:
```js
ConvertUPCAtoEAN13: true / false
```
If you don't want to break anything, you can let the default behaviour follow Android (strip the zero), but allow the developer to keep 13 digits if they use the flag.

**Comment by timdmackey** [comment]
Looking at the zxing library, it appears that the EAN_13 decoder adds a leading zero to UPC_A codes: [EAN13Reader.java#L117](https://github.com/zxing/zxing/blob/0cf3b9be71680f50c90a71ca26ce0d33664b0dd6/core/src/main/java/com/google/zxing/oned/EAN13Reader.java#L117), while the UPC_A decoder returns the code as is and just verifies that the first digit is a zero: [UPCAReader.java#L77](https://github.com/zxing/zxing/blob/0cf3b9be71680f50c90a71ca26ce0d33664b0dd6/core/src/main/java/com/google/zxing/oned/UPCAReader.java#L77)

**Comment by timdmackey** [comment]
Good call testing those other codes with extra zeros.

I think what you have now is good. The Firebase ML Kit implementation makes sense, so I think it probably makes sense for this plugin to behave similarly. i.e.- always report UPC_A as UPC_A, and don't add a leading zero. If a developer wants to treat UPC_A as a 13-digit EAN, it's easy enough for them to add the digit themselves.

One question—on the last chart, what do you mean by this?

UPC_A | EAN_13 | ✅reported as EAN_13 | ✅reported as EAN_13
-- | -- | -- | --

Does that mean that if you specify UPC_A you can still scan any EAN_13?

**Comment by timdmackey** [comment]
Took a look at the new commit, and it looks great. Thanks for working through this!

**Comment by timdmackey** [comment]
I guess this is a breaking change again! I think this is the correct solution though. 
> Because this is breaking change (a leading '0' will be dropped for EAN_13 codes which are actually UPC_A codes) so I decided to bump the major version.

**Comment by EddyVerbruggen** [comment]
You're right, I decided to go with 3.0.0 again (and just published it to npm). Thanks a million for all the support with this nasty issue!

**Comment by timdmackey** [comment]
Happy to help!
