### ISSUE TITLE
Cannot read property 'zxing' of undefined

### ISSUE THREAD

**Issue by Dhruvi109** [EddyVerbruggen/nativescript-barcodescanner#177]
we are getting issue : Cannot read property 'zxing' of undefined
 with nativescript version : 5.0.4 and "nativescript-barcodescanner": "2.7.8",

**Comment by EddyVerbruggen** [comment]
Please search the repo for similar issues: https://github.com/EddyVerbruggen/nativescript-barcodescanner/search?q=Cannot+read+property+%27zxing%27+of+undefined&type=Issues
