### ISSUE TITLE
[iOS & Angular] Open barcode scanner from a modal page not working

### ISSUE THREAD

**Issue by NickIliev** [EddyVerbruggen/nativescript-barcodescanner#183]
With the latest versions of NativeScript there is a possibility where you the app can have multiple frames and where the modals can be nested This changed the way the `rootViewController` is accessed.

The Scenario:
- Create an  Angular app with a modal and open the barcode scanner from the modal (which in practice opens another modal page).

Result: The barcode scanner won't open or the app will freeze/crash. Happens on iOS with Angular.

To resolve the issue, the view controller can be determined as done in the nativescript-camera plugin. [Here is the code that get a reference to the needed view controller ](https://github.com/NativeScript/nativescript-camera/blob/master/src/camera.ios.ts#L169-L187)(no matter if it is the topmost frame or the last known opened modal). 

In the case of nativescript-barcodescanner the same should be done when the scan is canceled, closed, finished ( when calling `dismissViewControllerAnimatedCompletion(true, null);`)

Demo app showing the modal issue attached here
[barcode-demo.zip](https://github.com/EddyVerbruggen/nativescript-barcodescanner/files/2828547/barcode-demo.zip)

**Comment by EddyVerbruggen** [comment]
I tried the code of nativescript-camera, but it actually didn't solve the issue. After adding a little timeout (only in case the app is showing a modal) it did though. In my tests with your demo and demo-ng (in this repo) the app no longer crashes on my iPhone X. Thanks for reporting!
