### ISSUE TITLE
Error in barcodescanner.scan: TypeError: Cannot read property 'zxing' of undefined

### ISSUE THREAD

**Issue by einicher** [EddyVerbruggen/nativescript-barcodescanner#19]
This seems to be a reappearing problem?

$ npm list
Groceries@1.0.0 /home/mre/sample-Groceries
├── nativescript-barcodescanner@1.3.2
└─┬ tns-core-modules@1.7.0
     └── tns-core-modules-widgets@1.7.0

**Comment by einicher** [comment]
also a build error (i'm no java dev):

Exception in thread "main" java.lang.IllegalArgumentException: Class com.tns.internal.AppBuilderCallback conflict: /home/mre/eTankApp/platforms/android/build/intermediates/classes/debug and /home/mre/eTankApp/platforms/android/build/intermediates/classes/nativescript-barcodescanner/debug
	at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
	at com.telerik.metadata.Builder.build(Builder.java:41)
	at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED

FAILURE: Build failed with an exception.

**Comment by EddyVerbruggen** [comment]
That doesn't sound like a plugin issue - have you tried removing the Android platform and adding it back again?

**Comment by einicher** [comment]
I removed platform android and readded it, now build works fine, but when i (using your demo) push one of the two camera buttons i get again:
JS: Error in barcodescanner.scan: TypeError: Cannot read property 'zxing' of undefined
JS: No scan. TypeError: Cannot read property 'zxing' of undefined
(available and has permission says “YES”)

**Comment by EddyVerbruggen** [comment]
Can I clone your repo from somewhere?

**Comment by einicher** [comment]
its weird, 
to give you a proper example an push it to a github repo i copied my testapp to another folder, stripped it from other stuff and rebuild it, now it works perfectly fine.

**Comment by tsvetan-ganev** [comment]
I also experienced the ```Cannot read property 'zxing' of undefined``` error. I could not figure out what caused it, but removing + adding the android platform several times fixed the issue.

**Comment by EddyVerbruggen** [comment]
Thanks for sharing guys. Removing the platform and adding it again (or starting a new project) should indeed help. But it's a bit of a pain of course.

**Comment by meiriko** [comment]
Try uninstalling the application and run "tns run..." again. Re-installing solved the problem for me
