### ISSUE TITLE
Adding Interleaved 2 of 5 (not ITF/ITF14) Barcode Type

### ISSUE THREAD

**Issue by freeurcom** [EddyVerbruggen/nativescript-barcodescanner#191]
Hello,

I noticed that the Barcode Type "Interleaved 2 of 5" is not included in the list of barcode types. Could you include that one? (as "ITF25" or something).

Ref: AVMetadataObjectTypeInterleaved2of5Code - https://developer.apple.com/documentation/avfoundation/avmetadataobjecttypeinterleaved2of5code?language=objc

Best regards
Reinhard

**Comment by EddyVerbruggen** [comment]
Hi, it's available now from npm - iOS only though. See the readme for details.
