### ISSUE TITLE
Scanenr freez android app if hit back button or navigate to another page

### ISSUE THREAD

**Issue by vforv** [EddyVerbruggen/nativescript-barcodescanner#193]
When I am in the scanner on Android device and click back button it close scanner and I am not able to  use app for few seconds it just freezs. Also it triggers error message: "Error when scanning Scan aborted".

Here is my code:

```
public onScan() {
    this.getScanner();
  }

  private getScanner() {
    this.barcodeScanner.scan({
      formats: "QR_CODE, EAN_13",
      cancelLabel: "Zatvori skener",
      showFlipCameraButton: false,
      preferFrontCamera: false,
      showTorchButton: true,
      beepOnScan: true,
      torchOn: false,
      resultDisplayDuration: 500,
      message: "Skenirajte QR kod da bi pristupili meniju",
      closeCallback: () => { console.log("Scanner closed") },
      openSettingsIfPermissionWasPreviouslyDenied: true //ios only 
    }).then((result: any) => {
      const qrDecoded = JSON.parse(result.text);
      this.qrEmitter.emit(qrDecoded);
    }, (errorMessage) => {
      console.log("Error when scanning " + errorMessage);
    }
    )
      .catch((error) => {
        console.log('cathced error', error);
      });
  }
```

I am using Angular and Nativescript

Edit:
I think I found here some solution:
https://stackoverflow.com/questions/38664956/in-fragment-how-to-stop-camera-of-zxing-scanner
But don't know how to implement in plugin

**Comment by valera1401** [comment]
Also faced this issue.

**Comment by vforv** [comment]
Add marking mode none in package.json in src file like this
```

"android": {
    "v8Flags": "--expose_gc",
    "markingMode": "none"
  },
```

**Comment by valera1401** [comment]
Thank you, it helped.

**Comment by s-nilewar** [comment]
Thank You! It helped me as well.

**Comment by EddyVerbruggen** [comment]
Thanks! I use that all the time as well, and it seems to be the default in {N} these days, so closing. Not much the plugin can do about it anyway.. and since it's the default now there's not much sense in documenting it. Still, folks searching for a similar issue on this repo will likely find this issue and your solution. 👍
