### ISSUE TITLE
Bug when scanning QR code

### ISSUE THREAD

**Issue by vforv** [EddyVerbruggen/nativescript-barcodescanner#195]
I'm using Angular + Nativescript
This error is from Iphone.

`CONSOLE LOG file:///app/vendor.js:81401:20: Unknown format scanned: QR_CODE, please report this at https://github.com/EddyVerbruggen/nativescript-barcodescanner/issues`

This is QR code I try to scan:

https://imgur.com/ZXI4icv

It returns correct result but still there is something not right.

**Comment by EddyVerbruggen** [comment]
Interestingly, I can't even scan that QR code with the demo app.

Can you successfully scan (for instance) this one? https://cdn.qrstuff.com/images/default_qrcode.png

It successfully reports type/format 'QR_CODE' for me.

**Comment by vforv** [comment]
I am able to scan and get result in console with iPhone 6s, but return error in console...

**Comment by EddyVerbruggen** [comment]
You get both a result and error in the console with the demo? Can you share a screenshot please, because I have a hard time figuring this one out.

**Comment by vforv** [comment]
Sure but have problem run another your plugin could you check it first: https://github.com/EddyVerbruggen/nativescript-feedback/issues/49

**Comment by vforv** [comment]
I solved, needed to remove content from pods in node_modules could you fix it in pkg?

Here is SS: https://i.ibb.co/crx9Bhq/Screenshot-2019-03-11-at-16-32-00.png

It works well, only problems is it show alert in console I don't know why...

**Comment by vforv** [comment]
> Sure but have problem run project, this plugin creates problem could you check it first? [EddyVerbruggen/nativescript-feedback#49](https://github.com/EddyVerbruggen/nativescript-feedback/issues/49)

Still problem not solved, pls check

**Comment by EddyVerbruggen** [comment]
Thanks @vforv, I'll look into that.

**Comment by EddyVerbruggen** [comment]
Hi @vforv, I found the incorrect logging. Indeed it didn't hamper usage, but it looked a bit scary. I've removed the offending code in 3.1.2 (now on npm).
