### ISSUE TITLE
Ionic support

### ISSUE THREAD

**Issue by SaltyPotato** [EddyVerbruggen/nativescript-barcodescanner#197]
Is this plugin compatible with ionic? If so, what would be the way to implement and use this in the ionic framework?

Thanks in advance!

**Comment by EddyVerbruggen** [comment]
Nope. Ionic requires a Cordova or Capacitor plugin and has a web-native bridge. NativeScript plugins don't have this bridge so you can't use this plugin in an Ionic app.

Btw, you *can* use a Cordova plugin in a NativeScript app, but that's off topic I think 😉

**Comment by EddyVerbruggen** [comment]
Oh, and the equivalent plugin for Ionic would be [this one](https://github.com/phonegap/phonegap-plugin-barcodescanner), but you probably knew that.

**Comment by SaltyPotato** [comment]
> Oh, and the equivalent plugin for Ionic would be [this one](https://github.com/phonegap/phonegap-plugin-barcodescanner), but you probably knew that.

Yes I'm aware of that, but it does not have the continuous scanning feature. Any plans of adding ionic support in the future?

**Comment by sonegs** [comment]
@jhgeluk ey did you find an alternative to this plugin? I can not use this phonegap plugin or this one to my ionic project
