### ISSUE TITLE
1D-Barcode scanning not working

### ISSUE THREAD

**Issue by sagheerahmad** [EddyVerbruggen/nativescript-barcodescanner#202]
Hi,
I am using the demo app for angular andoid and it works perfectly for 2D barcodes like DataMatrix and QR-Code. But it doesn't work for 1D barcode. i tried Code-128 barcodes as well using this https://barcode.tec-it.com/en/Code128?data=451009630567, but it cant scan.
can you please help me in this , does it hase support of 1D Barcodes for angular or not?

Thanks

**Comment by EddyVerbruggen** [comment]
Make sure your code is adjusted to allow scanning those: https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/a06f91cad346056abd677b5785da8a50d25388cd/demo-ng/app/item/item-detail.component.html#L11

**Comment by sagheerahmad** [comment]
Thanks EddyVerbruggen, it works 👍

**Comment by sagheerahmad** [comment]
Hi Eddy,
I have tested it on mobile phone and it works for 1D but i am using this device and on which the 1D barcode is not scanning , is there any limitation of the library on different devices.

https://www.xac.com.tw/tw/product/show.php?kind=Handheld%20&%20Desktop%20Terminal&num=47

Thanks
