### ISSUE TITLE
iOS: requestCameraPermission resolved too early

### ISSUE THREAD

**Issue by cindy-m** [EddyVerbruggen/nativescript-barcodescanner#203]
In our code, when the user uses the barcodescanner for the first time, we call the methode `requestCameraPermission`. Based on what the user choses, we either go to scan the code or show an alert that the permission was not granted for the functionality. The code looks like this:

```
this.barcodeScanner.requestCameraPermission()`
      .then(() => this._barcodeScanner.hasCameraPermission()) //workaround for Android
      .then((hasPermission: boolean) => {
        if (hasPermission) {
          this.scanQRCode();
        } else {
          this.showPermissionAlert();
        }
      })
      .catch(() => {
        this.showPermissionAlert();
      });
```
On iOS, it seems that the first time the user does get the alert with the question if he/she will grant camera acces, but in the code we saw with logging that the promise of the `requestCameraPermission` was already resolved and it is waiting in the `showPermissionAlert` function waiting till the alert is closed. So even when the user grants permission, he/she still will get the permission alert right after.
Shouldn't it be that the `requestCameraPermission` promise would only be resolved after the user grants or denies camera acces? 
Android works correctly as expected, this is only problem on iOS

**Comment by EddyVerbruggen** [comment]
Hi, did you check the iOS source to see if you can find the cause? Happy to merge a PR as always!

**Comment by kefahB** [comment]
Hi,

I have same issue with IOS, please try to use `camera.requestCameraPermissions()` from `nativescript-camera` instead of `barcodescanner.requestCameraPermission()`

**Comment by EddyVerbruggen** [comment]
@kefahB Good point, I'll take a look at [their implementation](https://github.com/NativeScript/nativescript-camera/blob/7b9e64898e73baf56f50c118d0889b6f0aa4dcba/src/camera.ios.ts#L247) and see if that can be applied to this plugin as well.

**Comment by kefahB** [comment]
Here is it : 
```ts
export let requestPhotosPermissions = function () {
    return new Promise(function (resolve, reject) {
        let authStatus = PHPhotoLibrary.authorizationStatus();
        switch (authStatus) {
            case PHAuthorizationStatus.NotDetermined: {
                PHPhotoLibrary.requestAuthorization((auth) => {
                    if (auth === PHAuthorizationStatus.Authorized) {
                        if (trace.isEnabled()) {
                            trace.write("Application can access photo library assets.", trace.categories.Debug);
                        }
                        resolve();
                    } else {
                        reject();
                    }
                });
                break;
            }
            case PHAuthorizationStatus.Authorized: {
                if (trace.isEnabled()) {
                    trace.write("Application can access photo library assets.", trace.categories.Debug);
                }
                resolve();
                break;
            }
            case PHAuthorizationStatus.Restricted:
            case PHAuthorizationStatus.Denied: {
                if (trace.isEnabled()) {
                    trace.write("Application can not access photo library assets.", trace.categories.Debug);
                }
                reject();
                break;
            }
        }
    });
};
```

**Comment by EddyVerbruggen** [comment]
Yep, I linked to that bit 😃- cheers mate!
