### ISSUE TITLE
1D barcode on specific device not working

### ISSUE THREAD

**Issue by sagheerahmad** [EddyVerbruggen/nativescript-barcodescanner#204]
Hi Eddy,
I have tested the demo application on mobile phone and it works for 1D but i am using this device and on which the 1D barcode is not scanning , is there any limitation of the library on different devices.

https://www.xac.com.tw/tw/product/show.php?kind=Handheld%20&%20Desktop%20Terminal&num=47

Thanks

**Comment by EddyVerbruggen** [comment]
I guess Google knows this better than I do. Search for ZXing icw your specific device.

**Comment by sagheerahmad** [comment]
Thanks
