### ISSUE TITLE
AndroidX compatibility

### ISSUE THREAD

**Issue by EddyVerbruggen** [EddyVerbruggen/nativescript-barcodescanner#209]
We need to dynamically detect and use AndroidX packages because of the way Google now treats support packages. Note that {N} 6 will be fully AndroidX compatible as well.

**Comment by andreabbondanza** [comment]
Hi, thanks for this upgrade for androidx support. When do you think to update this on npm? Actually I've the 3.2.0 but it miss the androidx support. 
Actually I'm working with the {N} 6-rc 
Thank you :)

**Comment by EddyVerbruggen** [comment]
Hi, I haven't finished implementing/testing these changes yet. I hope this week.

**Comment by EddyVerbruggen** [comment]
Well, it needed one more fix and now all seems fine. Publishing 3.2.1 in a sec.
