### ISSUE TITLE
Redirecting after scan [bug]

### ISSUE THREAD

**Issue by vforv** [EddyVerbruggen/nativescript-barcodescanner#210]
Sometimes app crashes... This is how I use scanner
1. Scan code
2. After get data redirect to other route

I belive there is some process which is interupted in scanner after I try redirection.
I think there should be some function which we can call to close scanner after promise is resolved.

Ex.

```
this.barcodeScanner.scan({
      formats: "QR_CODE, EAN_13",
      cancelLabel: "Zatvori skener",
      showFlipCameraButton: false,
      preferFrontCamera: false,
      showTorchButton: true,
      beepOnScan: true,
      torchOn: false,
      message: "Skenirajte QR kod da bi pristupili...",
      openSettingsIfPermissionWasPreviouslyDenied: true //ios only 
    }).then((result: any) => {
     //DO THINGS
     this.barcodeScanner.close();
 }
```

I am using Nativescript with Angular.
Could this be achived?

I see also this callback:

`closeCallback: () => { console.log("Scanner closed")}, // invoked when the scanner was closed (success or abort)`

What mean success or abort?
Is it possible with that to close scanner after successful scan and get data in that callback?

**Comment by EddyVerbruggen** [comment]
Abort = cancelled by the user.

I don't see a `continuousScanCallback` in your options so when a code is scanned the scanner closes. So please remove the line `this.barcodeScanner.close();`.

Also, can you try adding a timeout before redirecting? The close animation may interfere with the routing animation.

**Comment by vforv** [comment]
Hi @EddyVerbruggen, it looks like it fix in dev env but still not sure for prod. I can't tell for sure because it happen sometime.

Still I think it is not the best way, I think there should be way to automatically close the scanner, like modal and dialogs works, because there is a lot of applications where user don't want continuously to scan QR codes.  For example if someone just want to scan QR code and close the scanner. Do you think it is possible to integrate that?

**Comment by smorcuend** [comment]
Hi all,
I have the same problem on nativescript-angular. In my scenario i want to collect data from succesful QRCODE scanning and navigate to another route inside promise resolved but it seems that angular router is navigating to root path when activityResume event (on Android) fires the promise resolution.
I think that issue may be related with this one: https://github.com/NativeScript/nativescript-angular/issues/1726 because i experiment an app freezing for 5 seconds when promise is resolved also.

My code:
```  
 onScan() {
    this.processing = true;
    from(
      this.barcodeScanner.scan({
        formats: 'QR_CODE',
        showFlipCameraButton: true,
        preferFrontCamera: false,
        showTorchButton: true,
        beepOnScan: true,
        torchOn: false,
        resultDisplayDuration: 2000,
        orientation: 'portrait',
        closeCallback: () => {
          console.log('closeCb');
        }
      })
    )
      .pipe(
        catchError(val => of(`I caught: ${val}`))
      )
      .subscribe(
        result => {
          console.log('result scan Promise');
          this._ngZone.runTask(() => {
            this.processing = false;
            this.routerExtensions.navigate(['wizard/third-step'], {
              clearHistory: true
            });
          })
          
        },
        errorMessage => console.log('Error when scanning ' + errorMessage)
      );
  }
```
The scan function is wrappered with rxjs-observables.

My router:
```
const routes: Routes = [
  { path: 'login', component: LoginComponent },
  {
    path: 'welcome',
    component: WelcomeComponent
  },
  {
    path: 'wizard',
    loadChildren: '~/app/wizard/wizard.module#WizardModule',
  },
  { path: '', redirectTo: 'welcome', pathMatch: 'full' }
];
```

The result after scan QRCODE:
1. JS: closeCallback is called
2. JS: result scan Promise is reached
3. JS: navigation to root route event is fired
4. App freezes for 3-5 seconds
5. App navigates to root route

The code inside ngzone has no effect on app.

Probably this issue is caused by nativesctipr-angular complex layer.

Any idea?

Thanks @EddyVerbruggen for this amazing plugin.

**Comment by slaven3kopic** [comment]
@vforv @EddyVerbruggen to redirect successfully the module you are trying to redirect to can't be lazy loaded. Include WizardModule to AppModule imports and define { path: 'wizard', component: WizardComponent } in your wizard-routing.module.ts

**Comment by slaven3kopic** [comment]
@smorcuend  @EddyVerbruggen to redirect successfully the module you are trying to redirect to can't be lazy loaded. Include WizardModule to AppModule imports and define { path: 'wizard', component: WizardComponent } in your wizard-routing.module.ts
