### ISSUE TITLE
Resize scanner layout

### ISSUE THREAD

**Issue by dhruv270** [EddyVerbruggen/nativescript-barcodescanner#211]
I am facing issue about scanner size. When I open component, Scanner takes full screen but I want to fix its size. How can I achieve that?

![scanner UI](https://user-images.githubusercontent.com/19384097/60755402-e1cef800-a00c-11e9-9974-ddd48badb68d.jpeg)

**Comment by EddyVerbruggen** [comment]
On Android you can't embed the view in a larger view with this plugin (you can on iOS though). You can with the Firebase plugin when using the MLKit barcodescanner feature.

**Comment by ladaniavadh** [comment]
@EddyVerbruggen , it is showing the error on nativescript 7, 
is there any solution to work with ML on nativescript 7?
![image](https://user-images.githubusercontent.com/30779077/102358806-f40cde00-3fd5-11eb-8614-699dca212768.png)
