### ISSUE TITLE
Embedded scanner can't scan the same code twice in a row

### ISSUE THREAD

**Issue by JillevdW** [EddyVerbruggen/nativescript-barcodescanner#212]
When scanning barcodes with the embedded scanner on iOS, the scanner won't call the `scanResult` callback when the same code is scanned twice in a row. It will scan it again once another code has been scanned in between. This is probably by design but could there be a way to turn this off or replace it with a "cooldown" of sorts? Thanks.

**Comment by EddyVerbruggen** [comment]
Did you try adding `reportDuplicates="true"`?

**Comment by JillevdW** [comment]
Ah that solves it, I just looked right past that, thanks!
