### ISSUE TITLE
Improve UX by adding a close button for Android

### ISSUE THREAD

**Issue by phils-hub** [EddyVerbruggen/nativescript-barcodescanner#215]
Hi Eddy, I really like your plugin and kudos on the demos. I am preparing to use it for an app and, having spent much time on iOS, i was very surprised when trying the Android demo that i could not close the scanner. According to the API this is also platform specific. From a UX perspective this was quite confusing and the only option left is to kill the app. 

Any chance you can add this some time? Is there a specific reason the functionality only exists for iOS?

**Comment by EddyVerbruggen** [comment]
Hi, on Android folks are used to using the hardware back button. That's not a "thing" on iOS devices so that's what explains the difference. Nothing I can nor will do about that.
