### ISSUE TITLE
Support for NativeScript 6

### ISSUE THREAD

**Issue by Izrab** [EddyVerbruggen/nativescript-barcodescanner#216]
**Support for NS version 6, AndroidX, webpack-only workflow, NS6 stack, etc...**

**Comment by EddyVerbruggen** [comment]
Interestingly, Android actually works with NativeScript 6, but iOS didn't because `utils.ios.getter` has been removed. I'll fix that right now.

**Comment by Izrab** [comment]
Thanks, that was quick! 
But I'm wondering why is not Marketplace giving it **NS6-support badge**, like how it does to other many other plugins,
![image](https://user-images.githubusercontent.com/22328131/62163293-ed8da180-b2ce-11e9-83b9-1e0f0c9ef1b0.png)

**Comment by EddyVerbruggen** [comment]
@Izrab I have no idea what the logic behind that badge is, but rest assured it's compatible.
