### ISSUE TITLE
One scan then stops working

### ISSUE THREAD

**Issue by mrwrighty** [EddyVerbruggen/nativescript-barcodescanner#217]
When scanning a QR code, the camera opens and the overlay appears. The QR code scans and presents the dialog with info thats been found. Closing the dialog leaves the camera open but the scanning overlay has gone. Leaving the page and returning does not fix the problem and the barcode scanner does not re-appear until the app is closed and restarted.

Javascript below.

`
var BarcodeScanner = require("nativescript-barcodescanner").BarcodeScanner;
var barcodescanner = new BarcodeScanner();

barcodescanner.scan({
    formats: "QR_CODE, EAN_13",
//    cancelLabel: "EXIT. Also, try the volume buttons!", // iOS only, default 'Close'
//    cancelLabelBackgroundColor: "#333333", // iOS only, default '#000000' (black)
    //message: "Use the volume buttons for extra light", // Android only, default is 'Place a barcode inside the viewfinder rectangle to scan it.'
    showFlipCameraButton: false,   // default false
    preferFrontCamera: false,     // default false
    showTorchButton: true,        // default false
    beepOnScan: true,             // Play or Suppress beep on scan (default true)
    torchOn: false,               // launch with the flashlight on (default false)
    closeCallback: () => { console.log("Scanner closed")}, // invoked when the scanner was closed (success or abort)
//    resultDisplayDuration: 500,   // Android only, default 1500 (ms), set to 0 to disable echoing the scanned text
//    orientation: orientation,     // Android only, default undefined (sensor-driven orientation), other options: portrait|landscape
    openSettingsIfPermissionWasPreviouslyDenied: true // On iOS you can send the user to the settings app if access was previously denied
  }).then((result) => {
      // Note that this Promise is never invoked when a 'continuousScanCallback' function is provided
      alert({
        title: "Scan result",
        message: "Format: " + result.format + ",\nValue: " + result.text,
        okButtonText: "OK"
      });
    }, (errorMessage) => {
      console.log("No scan. " + errorMessage);
    }
  );
`

XML Below

`<Page loaded="pageLoaded" class="page" xmlns="http://www.nativescript.org/tns.xsd" xmlns:Barcode="nativescript-barcodescanner">

    <ActionBar title="Scan QR Tag" class="action-bar">
    </ActionBar>
    <GridLayout rows="*" width="100%" height="100%"
        backgroundColor="white">
        <iOS>
        <Barcode:BarcodeScannerView
      class="scanner-round"
      formats="QR_CODE, EAN_13"
      beepOnScan="true"
      reportDuplicates="true"
      preferFrontCamera="false"
      scanResult="onScanResult" />
        </iOS>
    </GridLayout>
</Page>`

**Comment by EddyVerbruggen** [comment]
What happens if you use console.log instead of alert?

**Comment by mrwrighty** [comment]
Ok will check tomorrow, but code is direct from example

**Comment by kefahB** [comment]
Hi @EddyVerbruggen 

I just come to reporting an issue is related not only with your plugin but with nay other plugin.

The issue come from `BottomNavigation` concept .. is the `IOS` that often affected by this issue .. if we use `Frame` in each `Tabs`  the plugin will work as long as you do not change the tab, if you change the tab and you go back to the tab who has the barcodescanner the `topmost()` or `Frame.topmost()` since NS +6.2 will return the last frame that has ben loaded .. and for this the plugin not work any more .. of cours you must close the app an reopen it...

My solution  momentally is to change all `frame.topmost()` on `barcodescanner.ios.ts` to `frame.topmost().page.frame` for NS < 6.2 or `frame.Frame.topmost().page.frame` for 6.2 and grater

What we should do in this case ?

```ts
BarcodeScanner.prototype.isPresentingModally = function () {
        var frame = require("tns-core-modules/ui/frame");
        var viewController;
        var topMostFrame = frame.Frame.topmost().page.frame;
        if (frame.Frame.topmost().page.frame) {
            viewController = topMostFrame.currentPage && topMostFrame.currentPage.ios;
            if (viewController) {
                while (viewController.parentViewController) {
                    viewController = viewController.parentViewController;
                }
                return !!viewController.presentedViewController;
            }
        }
        return false;
    };

BarcodeScanner.prototype.getViewControllerToPresentFrom = function (presentInRootViewController) {
        var frame = require("tns-core-modules/ui/frame");
        var viewController;
        var topMostFrame = frame.Frame.topmost().page.frame;
        if (topMostFrame && presentInRootViewController !== true) {
            viewController = topMostFrame.currentPage && topMostFrame.currentPage.ios;
            if (viewController) {
                while (viewController.parentViewController) {
                    viewController = viewController.parentViewController;
                }
                while (viewController.presentedViewController) {
                    viewController = viewController.presentedViewController;
                }
            }
        }
        if (!viewController) {
            viewController = UIApplication.sharedApplication.keyWindow.rootViewController;
        }
        this._lastScanViewController = viewController;
        return viewController;
    };

```
