### ISSUE TITLE
Does not work on android

### ISSUE THREAD

**Issue by terhoraj** [EddyVerbruggen/nativescript-barcodescanner#22]
I'm getting error with newest nativescript + android: "Cannot read property 'zxing' of undefined" please help, there's no other plugins like this for nativescript.

**Comment by EddyVerbruggen** [comment]
Does any of the [similar issues](https://github.com/EddyVerbruggen/nativescript-barcodescanner/search?q=Cannot+read+property&type=Issues&utf8=%E2%9C%93) help you in any way?

**Comment by terhoraj** [comment]
Thanks! I try especially[ this approach](https://github.com/EddyVerbruggen/nativescript-barcodescanner/issues/19) tomorrow

**Comment by meiriko** [comment]
Any news on this one? I'm having the same issue on android

**Comment by EddyVerbruggen** [comment]
If you're using `livesync` at least build once without it (`tns run android`) so the plugin is added correctly.
