### ISSUE TITLE
Camera usage after calling `barcodescanner.stop();`

### ISSUE THREAD

**Issue by erikverheij** [EddyVerbruggen/nativescript-barcodescanner#221]
Hi there,

Thank you for providing this awesome library!

In my app, it seems that the camera always stays on after starting a barcode scanner. Even after I call `barcodeScanner.stop()`. Is this the expected behavior? Will it drain the battery?

If it's not the expected behavior I might have another piece of my code that activates the camera.

**Comment by EddyVerbruggen** [comment]
Hey Erik, can you perhaps show your repo and mention the platform(s) you experience this on?

**Comment by erikverheij** [comment]
Hi Eddy. The platform is iOS. Unfortunately, I can't share the repo. However, I did some more research and found this:

```
// barcodescanner.ios.ts
  public stop(): Promise<any> {
    return new Promise((resolve, reject) => {
      try {
        this.close();
        this._removeVolumeObserver();
        this._closeCallback && this._closeCallback();
        resolve();
      } catch (ex) {
        reject(ex);
      }
    });
  }
```

The method does not call `this._reader.stopScanning();`. Does that mean the reader keeps "on"?

**Comment by EddyVerbruggen** [comment]
That makes sense actually, but I usually destroy the component which embeds the scanner so I wouldn't think it would stay active.. although I'm curious to learn how you use it (hence the request for a repo - preferrably a basic stripped-down version of your repo, or a Playground link).. and can you tell me how you noticed the scanner isn't stopped?

**Comment by erikverheij** [comment]
In our case the component is not destroyed as we use a modal to handle the follow-up. 

In this project I'm involved as product owner so I asked one of the developers about how we know that the scanner isn't stopped other than that the battery is draining very quickly. I've suggested using `console.log(barcodescanner._reader.running());` to find out whether it's still active. Unfortunately, the team didn't have the opportunity yet to try this. 

But I'm quite sure it's still running.. given that 1) we don't destroy the component 2) `this._reader.stopScanning();` has not been called 3) the battery is drains quickly even after calling `barcodeScanner.stop()`

In any way, I think it does make sense to always call `this._reader.stopScanning();` in `barcodeScanner.stop()`, doesn't it? I could think of other scenarios as well where you would want to pause scanning without destroying the element. For example if you want to implement a "Pause" button.

**Comment by EddyVerbruggen** [comment]
Hey Erik,

Thanks for the details, that all makes sense.

I've now published 3.4.0 which adds a `pause` property to the embedded scanner on iOS (since that's what I think you're using). If you set it to `true` it will now stop scanning. And setting it to `true` will resume scanning. See the updated README and `demo-ng` folder for an example.

**Comment by erikverheij** [comment]
Thanks for that fix, awesome!

**Comment by lucasumberto** [comment]
@EddyVerbruggen Just a point in this issue that might be relevant for someone or maybe a fix.

When the IOS BarcodeScanner vue component is turned off via v-if/else, you will not be able to stop it from scaning even changing the pause variable... it's just a thought, i didn't tested far to be sure.... I changed it to a v-show and the pause attribute worked.
