### ISSUE TITLE
embedding on Android

### ISSUE THREAD

**Issue by pacome2017** [EddyVerbruggen/nativescript-barcodescanner#222]
The readme informs that embedding a view is not supported on android platforms. However I managed to embed the android camera using another nativescript plugin, and you recommend using the firebase plugin to make it work. So my question is, will it be possible to modify this plugin to embed the camera in a view on android ?

**Comment by pacome2017** [comment]
I found this issue : 
#163 
I will try the workaround and report back

**Comment by EddyVerbruggen** [comment]
Nope.
