### ISSUE TITLE
Any way to enlarge the scanner message?

### ISSUE THREAD

**Issue by dominwong4** [EddyVerbruggen/nativescript-barcodescanner#224]

**Comment by EddyVerbruggen** [comment]
Please elaborate..

**Comment by dominwong4** [comment]
When we toggle the scanner, there is a message col that display Place a barcode inside the viewfinder rectangle to scan it as default message.

Can I enlarge the size of this text line?

**Comment by EddyVerbruggen** [comment]
I guess you mean on Android (a picture/screenshot would make it all so much clear)? But no, not without exposing it in the native library - which is possible of course.

**Comment by dominwong4** [comment]
Yes, you got what I mean. And sorry for lacking screenshot. 

Thanks
