### ISSUE TITLE
IOS 13 fullscreen

### ISSUE THREAD

**Issue by TommyVetZoo** [EddyVerbruggen/nativescript-barcodescanner#225]
Is it possible to make the barcodescanner open in fullscreen mode without the swipe functiononality added in ios13? 

Looking for something like in nativescipt-vue modal where you can add fullscreen:true to force the old functionality before ios13

**Comment by EddyVerbruggen** [comment]
I have no clue what you mean. Can you please share a video of what it does and what you want it to do?

**Comment by TommyVetZoo** [comment]
Thx for ansering, you can get it here:
http://bernietomsonmedia.com/barscan.mp4.zip

**Comment by TommyVetZoo** [comment]
Found a workaround
Added fullScreen:true to options in template and then in 
barcodescanner.ios.js -> BarcodeScanner.prototype.scan method
I replaced 
_this._scanner.modalPresentationStyle = 2;
with
var fs = arg.fullScreen ? UIModalPresentationStyle.fullScreen : 2
_this._scanner.modalPresentationStyle = fs;

**Comment by bartoszekj** [comment]
I confirm this bug in iOS 13. @TommyVetZoo Could you prepare PR ??

**Comment by EddyVerbruggen** [comment]
@TommyVetZoo That video was a huge help, thanks. I've added the `fullScreen` option as was suggested.

**Comment by TommyVetZoo** [comment]
That´s great! Thx for a great plugin! :)
MVH,

Tommy Berndtsson
CTO VetZoo.se

Mob: +46708970250




Den sön 10 nov. 2019 kl 20:17 skrev Eddy Verbruggen <
notifications@github.com>:

**Comment by TommyVetZoo** [comment]
Great! Thx for a great plugin :)
