### ISSUE TITLE
Execution failed for task ':app:processDebugManifest'

### ISSUE THREAD

**Issue by panagulis72** [EddyVerbruggen/nativescript-barcodescanner#227]
In my Nativescript/Angular application I have an issue running on Android:

`
	Attribute application@label value=(@string/clothes_app_name) from AndroidManifest.xml:11:159-195
	is also present at [:barcodescanner-release-2.1.6:] AndroidManifest.xml:11:18-50 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:11:5-40:19 to override.`

This is the <application> string of my manifest file:
`
    <application android:name="com.tns.NativeScriptApplication" tools:replace="android:allowBackup" android:allowBackup="false" android:icon="@drawable/icon" android:label="@string/clothes_app_name" android:theme="@style/AppTheme">`

and as you can notice I can't use 'tools:replace="android:label", as suggested by debug, because I'm already using tools:replace="android:allowBackup"

**Comment by GBManish1** [comment]
I am getting same issue , how is it resolved?
