### ISSUE TITLE
flashlight button

### ISSUE THREAD

**Issue by einicher** [EddyVerbruggen/nativescript-barcodescanner#23]
hi,
I think there is no easy way to add a flashlight on/off button to the scanning screen?

**Comment by EddyVerbruggen** [comment]
I've just added a way to enable/disable the flash by using the hardware volume up/down buttons respectively. If you hint your users in the app or through the in-scanner message then that's at least a step in the right direction, not?

It's available in 1.5.0 which is not on npm yet but you can test it by installing the plugin from github.

**Comment by EddyVerbruggen** [comment]
FYI The latest version has an option for iOS to add an on-screen button for a flashlight as well.
