### ISSUE TITLE
This dependency was not found

### ISSUE THREAD

**Issue by menthos984** [EddyVerbruggen/nativescript-barcodescanner#233]
I tried installing the package via npm install --save nativescript-barcodescanner but somehow after running the app, it prompts an error that the dependency was not found.

> This dependency was not found:

> * nativescript-barcodescanner in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/Form.vue?vue&type=script&lang=js&
> 
> To install it, you can run: npm install --save nativescript-barcodescanner

**Comment by EddyVerbruggen** [comment]
Better remove that dependency and use `tns plugin add nativescript-barcodescanner` instead.
