### ISSUE TITLE
Plugin does not work

### ISSUE THREAD

**Issue by smuellerus** [EddyVerbruggen/nativescript-barcodescanner#24]
As soon as I add this plugin to my project using

`tns plugin add nativescript-barcodescanner`

(without actually even using it), I can no longer build my project. The following error comes up:

```
:buildMetadata
Exception in thread "main" java.lang.IllegalArgumentException: Class com.tns.internal.AppBuilderCallback conflict: .../platforms/android/build/intermediates/classes/F0F1/debug and /home/smueller/Products/vesino-ticket/platforms/android/build/intermediates/classes/F0/debug
	at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
	at com.telerik.metadata.Builder.build(Builder.java:42)
	at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildMetadata'.
> Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 34.664 secs
Command .../platforms/android/gradlew failed with exit code 1
````

I just checked: This even happens with an empty project created with `tns create`.

What's wrong?

**Comment by EddyVerbruggen** [comment]
Can you try enabling multidex in your gradle configuration? See [this readme](https://github.com/EddyVerbruggen/nativescript-plugin-firebase) for details.

**Comment by smuellerus** [comment]
It now works, thank you for the quick support!

I got really frustrated with this, as I wasted 2 hours trying to get this
to work...

**Comment by EddyVerbruggen** [comment]
Still better than the 20 hours it took me to build it ;)
