### ISSUE TITLE
NativeScript 7 Support

### ISSUE THREAD

**Issue by hrueger** [EddyVerbruggen/nativescript-barcodescanner#244]
Could you please add support for NativeScript 7?

https://nativescript.org/blog/nativescript-7-for-plugin-authors/
https://nativescript.org/blog/nativescript-7-compatible-plugins/

**Comment by AndresGnu** [comment]
Review this fork: https://github.com/nativescript-community/ui-barcodeview

**Comment by EddyVerbruggen** [comment]
Please update to 4.0.0 (available on npm now). Or use that fork.
