### ISSUE TITLE
Nativescript 7 and barcode scanner 4.0.0

### ISSUE THREAD

**Issue by MitkoTschimev** [EddyVerbruggen/nativescript-barcodescanner#246]
Hi,

I tried the new package but receiving following error:

```
CONSOLE ERROR: ERROR Error: Uncaught (in promise): ReferenceError: NativeClass is not defined
ReferenceError: NativeClass is not defined
at Object.../node_modules/nativescript-barcodescanner/barcodescanner.js (file: node_modules/nativescript-barcodescanner/barcodescanner.ios.js:446:0)
at __webpack_require__ (file: src/webpack/bootstrap:74:0)
at Object../app/features/shared/components/scanner/scanner.provider.ts (file: src/app/features/shared/components/scanner/scanner.provider.ts:1:0)
```

so the problem comes already from the import:

import { BarcodeScanner } from 'nativescript-barcodescanner'; -> scanner.provider.ts:1:0

Seems like he doesn't know about this line of code:
````
QRCodeReaderDelegateImpl = QRCodeReaderDelegateImpl_1 = __decorate([
    NativeClass
], QRCodeReaderDelegateImpl);
```
I was already doing a `ns clean`

Any idea what could be the problem?

```
"dependencies": {
    "@nativescript/angular": "10.1.0",
    "@nativescript/core": "7.0.3",
    "@nativescript/firebase": "^11.0.0-rc.5",
    "@nativescript/shared-notification-delegate": "^1.0.0",
    "@nativescript/theme": "~2.5.0",
    "nativescript-barcodescanner": "^4.0.0",
    "nativescript-dev-version": "^0.2.0",
    "nativescript-numeric-keyboard": "^4.3.1",
    "nativescript-ui-listview": "^9.0.2"
  },
  "devDependencies": {
    "@nativescript/android": "~7.0.0",
    "@nativescript/ios": "7.0.0",
    "@nativescript/types": "~7.0.3",
    "@nativescript/webpack": "3.0.4"
  },
```

**Comment by ethnovode** [comment]
Same here.

**Comment by EddyVerbruggen** [comment]
I just ran the demo app with NativeScript 7 and version 4 of the plugin. Not having this issue on iOS.

Is there a (focused) repo I can look at?

**Comment by ethnovode** [comment]
Hello Eddy,

The "demo" seems to work fine but the "demo-vue" triggers this error.

My app uses vue.

Thanks!

**Comment by MitkoTschimev** [comment]
I don't have a repo for sharing maybe someone else?
I switched to the MLkit from firebase because I use it anyway and it works for me perfect. So this is what I can suggest if someone uses firebase.

**Comment by alexander-mai** [comment]
I have the same problem on Angular.

When I use the "Webpack usage" with provider and useFactory, i get the following error message:

```
***** Fatal JavaScript exception - application has been terminated. *****
NativeScript encountered a fatal error: Uncaught ReferenceError: NativeClass is not defined
at
../node_modules/nativescript-barcodescanner/barcodescanner.js(file: node_modules/nativescript-barcodescanner/barcodescanner.ios.js:446:0)
at __webpack_require__(file: src/webpack/bootstrap:816:0)
at fn(file: src/webpack/bootstrap:120:0)
at ./app/app.module.ts(file: src/app/app.module.ts:1:0)
at __webpack_require__(file: src/webpack/bootstrap:816:0)
at fn(file: src/webpack/bootstrap:120:0)
at (file:///app/bundle.js:3489:73)
at ./main.ts(file:///app/bundle.js:3541:30)
at __webpack_require__(file: src/webpack/bootstrap:816:0)
at checkDeferredModules(file: src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file: src/webpack/bootstrap:30:0)
at (file:///app/bundle.js:2:57)
at require(:1:137)
```

This is the part of the barcodescanner.ios.js (line 445 to 447:
```
QRCodeReaderDelegateImpl = QRCodeReaderDelegateImpl_1 = __decorate([
    NativeClass
], QRCodeReaderDelegateImpl);
```

**Comment by mwagena** [comment]
Having the same error, attached is a repository with a sample project.

https://github.com/mwagena/ns-barcode-scanner

**Comment by EddyVerbruggen** [comment]
Thx, any suggestions/PR for a fix as well perhaps?

**Comment by mwagena** [comment]
> Thx, any suggestions/PR for a fix as well perhaps?

sadly not, only thing I could provide you with is a test case...

**Comment by trevortos** [comment]
Im having the same issue. Not using Vue or Angular
I think the "NativeClass" thing is a bigger issue.

**Comment by NathanWalker** [comment]
@EddyVerbruggen i can help ya out here. just a moment.

**Comment by NathanWalker** [comment]
Here's the PR for proper {N} 7 support - possible @EddyVerbruggen we may could bring this one into https://github.com/NativeScript/plugins as well but either way you can merge then clean/build the plugin and publish and {N} 7 will be all good here too 👍 
https://github.com/EddyVerbruggen/nativescript-barcodescanner/pull/248

**Comment by AjiteshMDK** [comment]
Hi @NathanWalker Hi @EddyVerbruggen Hi @mwagena , 

I'm also having the same issue. Any idea what exactly i'm missing and how to fix this? Any pointer would be really helpful.

Link to my repo. - https://github.com/AjiteshMDK/GeoLocation-Update/

**NativeScript encountered a fatal error: Uncaught ReferenceError: NativeClass is not defined**
![image](https://user-images.githubusercontent.com/86408441/154277540-dc46c158-d274-4818-bbbe-adbffe363a44.png)
