### ISSUE TITLE
barcodescanner version for nativescript 6.5 

### ISSUE THREAD

**Issue by rellikdb1978** [EddyVerbruggen/nativescript-barcodescanner#247]
Hi,

I tried using the barcodescanner version 4.0.0 on nativescript 6.5.0 and it fails with
ERROR Cannot read property 'getApplicationContext' of undefined
at BarcodeScanner.wasCameraPermissionGranted (file: node_modules\nativescript-barcodescanner\barcodescanner.android.js:39:0)

inspected the line of code it uses "utils.ad" which is present only in nativescript 7.0 

i cannot move to NS7 right now. what is the fix?

**Comment by EddyVerbruggen** [comment]
That's 4.0.0 is a new major version (which suggest breaking changes) - it's at the top of the readme: https://github.com/EddyVerbruggen/nativescript-barcodescanner#nativescript-barcodescanner

**Comment by rellikdb1978** [comment]
Thanks that worked.
