### ISSUE TITLE
App crashes on Scan Button (ios 14)

### ISSUE THREAD

**Issue by Peter3101** [EddyVerbruggen/nativescript-barcodescanner#257]
Hello,

i have a problem with the plugin. I get the message: 

CONSOLE LOG: Error in barcodescanner.scan: TypeError: Cannot set property 'modalPresentationStyle' of null
CONSOLE LOG: Error when scanning TypeError: Cannot set property 'modalPresentationStyle' of null

and nothing happens.

The plugin has the version 4.0.1
and im running on nativescript angular 7.2.0

Thank you!

**Comment by trevormackay** [comment]
Hey Peter3101, 
I too had this error with 
plugin version 4.0.1 
nativescript vanilla ios 7.2.0
I set beepOnScan: false and removed platform ios and re-built the app and it works.
I'm logging this as Eddie requested.

ie...
barcodescanner.scan({
      formats: "QR_CODE,PDF_417,CODE_128,UPC_E,UPC_A",  
      beepOnScan: false, 
      ...
      
Cheers!

**Comment by Peter3101** [comment]
Hello trevormackay,
thank you for your hint. I have already seen to set Beeponscan to false. 

Finally „ns clean“ did the trick.
