### ISSUE TITLE
TypeError: viewClass is not a constructor

### ISSUE THREAD

**Issue by Salahudeen** [EddyVerbruggen/nativescript-barcodescanner#258]
Using nativesript with angular and i get the following error... please help.

 "@nativescript/angular": "~11.0.0",
 "@nativescript/core": "~7.1.0",
 "nativescript-barcodescanner": "^4.0.1",

JS:  ERROR  ERROR Error: Uncaught (in promise): TypeError: viewClass is not a constructor
JS: TypeError: viewClass is not a constructor
JS:     at ViewUtil.createView (file:///data/user/0/org.nativescript.barcode/files/app/vendor.js:105171:22)
JS:     at NativeScriptRenderer.createElement

**Comment by idevarts** [comment]
so what the solution ? i've got same error
