### ISSUE TITLE
Getting error on fresh hello-world-ng app: Can't find variable: QRCodeReaderDelegate

### ISSUE THREAD

**Issue by hugheba** [EddyVerbruggen/nativescript-barcodescanner#27]
I created a fresh app and installed the plugin, now getting 

`Jul  8 14:53:11 Mac-Pro mobile[47233]: 1   0xa025c -[TNSRuntime executeModule:]
Jul  8 14:53:11 Mac-Pro mobile[47233]: 2   0x5203b main
Jul  8 14:53:11 Mac-Pro mobile[47233]: 3   0x3cfda25 start
Jul  8 14:53:11 Mac-Pro mobile[47233]: 4   0x1
Jul  8 14:53:11 Mac-Pro mobile[47233]: file:///app/tns_modules/nativescript-barcodescanner/barcodescanner.js:96:65: JS ERROR ReferenceError: Can't find variable: QRCodeReaderDelegate
Jul  8 14:53:11 Mac-Pro com.apple.CoreSimulator.SimDevice.7B84929E-6CC8-4BC4-8002-D96E18C01083.launchd_sim[42146] (UIKitApplication:org.nativescript.mobile[0x741e][47233]): Service exited due to signal: Segmentation fault: 11`

`tns create mobile --template https://github.com/NativeScript/template-hello-world-ng`

Added iOS platform and the nativescript-barcodescanner plugin then ran livesync in the emulator.

**Comment by EddyVerbruggen** [comment]
Thanks. Let me try that tomorrow.

**Comment by sosofr74** [comment]
I get the same issue, running my app on ios emulator with nativescript 2.0.1

**Comment by EddyVerbruggen** [comment]
The only reason I can think of is you're running it on pre-iOS8.. Just test again on 8.4 without issue.

NativeScript 2.1.1
Node 4.2.2

**Comment by hugheba** [comment]
Building succeeds, error happens while trying to develop:

`tns livesync ios --emulator --watch`

Added `IPHONEOS_DEPLOYMENT_TARGET = 9.3` to build.xcconfig and that what's reported on build.

Nativescript: 2.1.1
Simulator: iPhone 6 / iOS 9.3 (13E230)

**Comment by sm1ddy** [comment]
Same error here as well.

**Comment by EddyVerbruggen** [comment]
Please share you project(s) with me as I just can't reproduce this issue..

**Comment by bnussey** [comment]
Hey @EddyVerbruggen I'm getting the same error on iOS emulator. Project is pretty standard but it is ng2.. could that be impacting it?

**Comment by bnussey** [comment]
I'm running:
```
nativescript     │ 2.2.1
tns-core-modules │ 2.2.1
tns-android      │ 2.2.0
tns-ios          │ 2.2.1
```

**Comment by bnussey** [comment]
Hey all I was able to get around this issue by doing `tns run ios --emulator` as opposed to using `tns livesync ios --emulator` .. you may need to do a `tns platform remove ios` and `tns platform add ios` before doing this. if that still doesn't work, let me know.

**Comment by EddyVerbruggen** [comment]
Thanks @bnussey I hope this info will be useful for others when they search the repo / Google for a similar issue 👍
