### ISSUE TITLE
Adding another NativeScript TNS module with Library project

### ISSUE THREAD

**Issue by dukhanov** [EddyVerbruggen/nativescript-barcodescanner#3]
Hello, 
Thanks you for awesome TNS module.

I have a question about adding another module:
What if I have added the BarcodeScanner module and I want to add another module with the Labrary project?
Will this work?

I think the latest added module will override the LabraryProject folder. Is not it?
![image](https://cloud.githubusercontent.com/assets/11015670/9406824/7f6c22de-480c-11e5-945e-f5289560f041.png)

**Comment by EddyVerbruggen** [comment]
Good question! I think you're right. Perhaps the CLI should fix these issues for us, but it may be a good idea to try and change that foldername.

**Comment by dukhanov** [comment]
I hope, if you change the folder name, it will work.

Thanks a lot!

**Comment by EddyVerbruggen** [comment]
A bit late, but this project no longer has this folder, simply an .aar so that's fixed.
