### ISSUE TITLE
Scan from image feature request

### ISSUE THREAD

**Issue by bnussey** [EddyVerbruggen/nativescript-barcodescanner#30]
The ability to scan from an image, as opposed to the camera, would be a fantastic addition to this plugin

**Comment by EddyVerbruggen** [comment]
I agree.

On Android the ZXing lib used is supposed to support this, so should be fairly easy.

On iOS there's a built-in [detector type for QR codes](https://developer.apple.com/library/ios/documentation/CoreImage/Reference/CIDetector_Ref/#//apple_ref/doc/constant_group/Detector_Types) which should do the trick.

The question is: would recognizing QR code be sufficient, or do you need 1D barcodes as well?

**Comment by bnussey** [comment]
Hey @EddyVerbruggen we would ideally like to use it with `PDF_417`. Would that be possible with this iOS built-in detector?

**Comment by EddyVerbruggen** [comment]
Hmm I doubt it as the name suggests it does only QR codes. [And this official doc.](https://developer.apple.com/reference/coreimage/cidetectortypeqrcode)

Perhaps [this JS decoder](https://github.com/PeculiarVentures/js-zxing-pdf417) works on iOS..

**Comment by bnussey** [comment]
Ok great thanks for the link, I might try and experiment with this decoder and see if it works.

**Comment by bnussey** [comment]
Hey @EddyVerbruggen this functionality now exists in `nativescript-ZXing` - https://github.com/NathanaelA/nativescript-zxing/ and is working well. Only problem is there is now a conflict between the two plugins and they cannot be run simultaneously. Its the `Execution failed for task ':buildMetadata'.` error and looks like you've had this before as per https://github.com/EddyVerbruggen/nativescript-local-notifications/issues/5 - think we might need to convert to a gradle?

**Comment by bnussey** [comment]
Any thoughts on this @EddyVerbruggen

**Comment by EddyVerbruggen** [comment]
@bnussey Not yet, had a bit of a busy OSS week..

<img width="30" alt="screen shot 2016-09-12 at 22 35 50" src="https://cloud.githubusercontent.com/assets/1426370/18451938/51260296-7939-11e6-9f3b-53e2f7042567.png">

**Comment by NathanaelA** [comment]
@bnussey - actually this is easy to fix.  Install both plugins like normal.  Manually navigate to node_modules/nativescript-zxing/platforms and then DELETE the android platform, before you build your app.    My plugin source should be able to use Eddy's version of ZXing on Android fine.

**Comment by joeskeen** [comment]
👍 This would be a useful feature (scanning QR from image) for when testing in the iOS Simulator where it's impossible to use the camera.

**Comment by NathanaelA** [comment]
@joeskeen - If you use my plugin with Eddys then you will get both local scan and camera scan.    HOWEVER, as a word of warning -- ZXing QR Code scans only work if the content is "text".   If the QRCode format is binary; zxing will return garbage (effects both my plugin and Eddys).  This is a corner case as most qr's are text coded; but just a heads up.
