### ISSUE TITLE
Error: Cannot read property 'startActivityForResult', Android 4.4.2

### ISSUE THREAD

**Issue by lionMehanik** [EddyVerbruggen/nativescript-barcodescanner#31]
JS: Error in barcodescanner.scan: TypeError: Cannot read property 'startActivityForResult' of undefined (on Android 4.4.2 LG G2).

**Comment by EddyVerbruggen** [comment]
Is this perhaps on a second invocation of the scanner, or directly at startup?

**Comment by lionMehanik** [comment]
Hi. At startup.

**Comment by EddyVerbruggen** [comment]
Sorry for the late reply; wait until the app has started before invoking the scanner please.
