### ISSUE TITLE
Add support for MaxiCode on iOS

### ISSUE THREAD

**Issue by zhaoshengjun** [EddyVerbruggen/nativescript-barcodescanner#32]
Hi Eddy,

Just tried this plugin, works great! I am facing a small issue here with MaxiCode on iOS. 

As you specified in the readme file, MaxiCode is only supported in Android. But I wonder if you can add it to iOS as well? I've found some code on github: 

https://github.com/TheThingSystem/steward-ios-library/tree/master/Bootstrap/ZXingObjC/maxicode

Please check it. Thanks!

**Comment by EddyVerbruggen** [comment]
On iOS we can only scan types which are built in to the iOS scanner. [Full list here](https://developer.xamarin.com/api/type/AVFoundation.AVMetadataObjectType/), Apple doesn't support Maxicode and I'm not switching to ZXing.
