### ISSUE TITLE
UIApplication.sharedApplication is not a function

### ISSUE THREAD

**Issue by guru1966** [EddyVerbruggen/nativescript-barcodescanner#33]
While testing on iOS 10.0 with latest tns 2.3.0 I got the following error:

file:///app/tns_modules/nativescript-barcodescanner/barcodescanner.js:89:36: JS ERROR TypeError: UIApplication.sharedApplication is not a function. (In 'UIApplication.sharedApplication()', 'UIApplication.sharedApplication' is an instance of UIApplication)

This issue will be solved if I remove () in barcodescanner.ios.js from:
  UIApplication.sharedApplication().keyWindow.rootViewController.dismissViewControllerAnimatedCompletion(true, null);

to:
  UIApplication.sharedApplication.keyWindow.rootViewController.dismissViewControllerAnimatedCompletion(true, null);

Since this is not a function, any more ?? Does anybody know why this is an issue now ?

**Comment by EddyVerbruggen** [comment]
Hi, iOS 10 changed a bunch of methods to properties which causes these issues.

There's an easy way to fix it in a backward-compatible manner which I'll do later today.

Thanks for the heads-up!

**Comment by EddyVerbruggen** [comment]
Hi, can you please give the master branch of this GitHub repo a spin? It should fix that problem when building with iOS 10. I can't upgrade until the end of the week, so that's why I'd appreciate a test by you before publishing to npm.

**Comment by EddyVerbruggen** [comment]
Updated to Xcode 8 and confirmed it works fine now. Please use plugin version 1.3.6.

**Comment by EricRobertBrewer** [comment]
I have had this issue once before. In ***my*** case, I fixed it using.

    var utils = require('utils/utils');
    ...
        var sharedApplication = utils.ios.getter(UIApplication, UIApplication.sharedApplication);

or, using Angular2:

    import * as utils from "utils/utils";
    ...
        let sharedApplication = utils.ios.getter(UIApplication, UIApplication.sharedApplication);

**Comment by EddyVerbruggen** [comment]
@EricRobertBrewer Yeah that's what was changed here as well 😉  - see the commits referenced in this issue.
