### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by Robophil** [EddyVerbruggen/nativescript-barcodescanner#34]
Hi @EddyVerbruggen when i try scanning i get "Configuration error" logged on my console which is supposedly next to impossible at the comment says.. lol.

Please help me out here

**Comment by EddyVerbruggen** [comment]
That's amazing! Does this happen all the time? If so, can you try 1.3.5 to see if that solves it?

Also, which device and Android version is this?

**Comment by Robophil** [comment]
Thanks. An upgrade fixed this.

**Comment by pgrzeszczak** [comment]
Hi, I have same issue now, with barcodescanner@2.1.0. Here's my config:
Phone: Nexus 5X
Android: 7.0 (security updates - 5 october)
Nativescript 2.3.0
App dependencies
```
"nativescript": {
    "id": "",
    "tns-android": {
      "version": "2.3.0"
    }
  },
  "dependencies": {
    "@angular/common": "2.1.0",
    "@angular/compiler": "2.1.0",
    "@angular/core": "2.1.0",
    "@angular/forms": "2.1.0",
    "@angular/http": "2.1.0",
    "@angular/platform-browser": "2.1.0",
    "@angular/platform-browser-dynamic": "2.1.0",
    "@angular/router": "3.1.0",
    "base-64": "^0.1.0",
    "lodash": "^4.16.4",
    "moment": "^2.15.1",
    "nativescript-angular": "1.1.0",
    "nativescript-barcodescanner": "^2.1.0",
    "nativescript-theme-core": "^0.1.2",
    "reflect-metadata": "~0.1.8",
    "tns-core-modules": "2.3.0",
    "utf8": "^2.1.1"
  },
  "devDependencies": {
    "babel-traverse": "6.16.0",
    "babel-types": "6.16.0",
    "babylon": "6.11.6",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^2.0.3",
    "zone.js": "~0.6.21"
  }
```
Previously I had angular 2.0.1 and barcodescanner 1.4.1 and everything worked perfectly. After dependencies update, asking for permission works fine, but scan returns: "JS: No scan: Configuration error"

**Comment by Robophil** [comment]
```bash
tns platform remove android
```
then
```bash
tns platform add android
```
should get it fixed. I can see your now using version 2.3.0

**Comment by hypery2k** [comment]
having this problem, too and re-adding platform does not help. Any suggestions? I tried wrapping it up in an Angular Service

**Comment by OliverNiebsch** [comment]
Checking if all needed permissions are in the AndroidManifest.xml fixed this kind of bug for me.
