### ISSUE TITLE
App Crash after scanning a barcode (Android)

### ISSUE THREAD

**Issue by imkrish** [EddyVerbruggen/nativescript-barcodescanner#39]
This is my package.json

"dependencies": {
    "@angular/common": "2.1.0",
    "@angular/compiler": "2.1.0",
    "@angular/core": "2.1.0",
    "@angular/forms": "2.1.0",
    "@angular/http": "2.1.0",
    "@angular/platform-browser": "2.1.0",
    "@angular/platform-browser-dynamic": "2.1.0",
    "@angular/router": "3.1.0",
    "nativescript-angular": "1.1.0",
    "nativescript-barcodescanner": "^2.1.1",
    "nativescript-drawingpad": "^1.1.1",
    "nativescript-geolocation": "0.0.13",
    "nativescript-theme-core": "^0.1.2",
    "reflect-metadata": "~0.1.8",
    "tns-core-modules": "^2.4.0-2016-10-17-4410"
  },
  "devDependencies": {
    "babel-traverse": "6.16.0",
    "babel-types": "6.16.0",
    "babylon": "6.12.0",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.3.2",
    "typescript": "^2.0.3",
    "zone.js": "~0.6.21"
  }

I fix a problem by removing these 4 lines of code in barcodescanner.android.js

// if (self.rememberedContext !== null) {
//     appModule.android.currentContext = self.rememberedContext;
//     self.rememberedContext = null;
// }

And now my app working fine but could you check or tell me a problem, please?

Thanks

**Comment by AdrianAaronGM** [comment]
Same problem using "nativescript-barcodescanner": "^2.1.3".
"Cannot set property currentContext of [object Object] which has only a getter"
It's also fixed using @imkrish solution.
