### ISSUE TITLE
 Cannot read property 'zxing' of undefined

### ISSUE THREAD

**Issue by Mararesliu** [EddyVerbruggen/nativescript-barcodescanner#4]
plugin had been added. but error.
V/JS      ( 1313): Error in barcodescanner.scan: TypeError: Cannot read property 'zxing' of undefined
V/JS      ( 1313): No scan: TypeError: Cannot read property 'zxing' of undefined

**Comment by Mararesliu** [comment]
nativescript-barcodescanner plugin can not be prepared for android.
but ios prepare ok. and will  create  lib/iOS/BarcodeScannerFramework.framework
but not lib/android.

**Comment by Mararesliu** [comment]
i found the problem may be nativescript new version. barcodescanner plugin  on android platform LibraryProject not be complied. 
i manual compile use ant debug build. the "'zxing' of undefined" is gone,
but app raise error, "android.content.res.Resources NotFoundException: Resource ID #0X0"

**Comment by aki009** [comment]
I've had the same issues. I had the same Resources NotFoundException when tried to manually compile.

**Comment by Mararesliu** [comment]
manually complie with ant release would meet other problem
:dexDebug
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Lcom/google/zxing/client/android/CaptureActivity;

**Comment by EddyVerbruggen** [comment]
Hey guys, I will look into this issue tomorrow and report back here.

**Comment by EddyVerbruggen** [comment]
Update: asking the {N} wizards for advice: https://github.com/NativeScript/nativescript-cli/issues/1059

**Comment by EddyVerbruggen** [comment]
Please update the plugin to 1.1.0, available [on npm](https://www.npmjs.com/package/nativescript-barcodescanner) as usual.
