### ISSUE TITLE
Angular Usage Docs Need Updating

### ISSUE THREAD

**Issue by joeskeen** [EddyVerbruggen/nativescript-barcodescanner#40]
I saw that recently for 2.0 you converted everything over to TypeScript and exposed a class.  I think this is great!  With this change, we will need to update the documentation for using it in Angular.  It should be much simpler now that you are exposing a class - we shouldn't need any of the `OpaqueToken` stuff anymore.

I'd be happy to update the docs myself but I don't quite have the time today, so I thought I would open this issue to track this until I can submit the PR.

**Comment by EddyVerbruggen** [comment]
That would be great, Joe! Thanks :)
