### ISSUE TITLE
iOS Barcode Scanning is Broken

### ISSUE THREAD

**Issue by joeskeen** [EddyVerbruggen/nativescript-barcodescanner#41]
After updating to the latest version of `nativescript-barcodescanner` from NPM, I was able to bootstrap it into my Angular 2 NativeScript app; however, when calling the `scan` function, I received an error:

```
Oct 19 16:25:58 mycomputer myapp[84719]: CONSOLE LOG file:///app/tns_modules/nativescript-barcodescanner/barcodescanner.js:175:28: Error in barcodescanner.scan: 
TypeError: QRCodeReaderViewController.readerWithCancelButtonTitleCodeReaderStartScanningAtLoadShowSwitchCameraButtonShowTorchButton 
is not a function. (In 'QRCodeReaderViewController.readerWithCancelButtonTitleCodeReaderStartScanningAtLoadShowSwitchCameraButtonShowTorchButton(closeButtonLabel, reader, startScanningAtLoad, flip, torch)', 'QRCodeReaderViewController.readerWithCancelButton
TitleCodeReaderStartScanningAtLoadShowSwitchCameraButtonShowTorchButton' is undefined)
```

Looking at [the source](https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/master/barcodescanner.ios.ts#L8) it looks like you have a lot of stuff commented out... perhaps things aren't in the best state?

As soon as this is fixed I can complete my work on https://github.com/EddyVerbruggen/nativescript-barcodescanner/issues/40 .

**Comment by EddyVerbruggen** [comment]
That commented source is on purpose, nothing to worry about. I updated the embedded framework, the new one has that methods it's complaining about so I think you'll need to do a `tns platform remove ios && tns platform add ios` and clear the lib/ios folder (in the root of your app).

**Comment by joeskeen** [comment]
Thanks @EddyVerbruggen I finally was able to try this out and it is working for me now.
