### ISSUE TITLE
No callbacks . the component re-render itself without any callbacks after the scannanig !

### ISSUE THREAD

**Issue by MomenYasser** [EddyVerbruggen/nativescript-barcodescanner#43]
I'm using nativescript-angular and there's not any callback after scaning . the component just re-render itself ! 

// module file 

```
@NgModule({
  providers: [
    <ValueProvider>{ provide: BARCODE_SCANNER, useValue: barcodescanner }
  ],
```

// barcodescaner

```
import { OpaqueToken } from '@angular/core';
import * as scanner from 'nativescript-barcodescanner';

export const BARCODE_SCANNER = new OpaqueToken('barcodescanner');

export const barcodescanner = new scanner.BarcodeScanner();
export type BarcodeScanner = scanner.BarcodeScanner;
export type ScanOptions = scanner.ScanOptions;
export type IosScanOptions = scanner.IOS;
export type AndroidScanOptions = scanner.Android;
```

// component file 

```
import { BARCODE_SCANNER, BarcodeScanner } from './barcodescanner';

scan(){
    this.barcodeScanner.scan({
      formats: "QR_CODE",
      message: "Place a barcode inside the viewfinder rectangle to scan it",
      preferFrontCamera: true,
      showFlipCameraButton: false,
      orientation: "landscape"
    })
    .then((result) => {
       this.login(result);
    },
    (error) => {
      this.loginError = true;
    });
  }
```

**Comment by EddyVerbruggen** [comment]
It's a bit hard for me to draw conclusions from a few code snippets, but can your replace `this.login(result);` by `console.log("scan callback");` ?

**Comment by MomenYasser** [comment]
Ok, i did but still not logging anything... Component just reload. Let's say i have added console log 'hi' in component constructor. After scanning it will console log 'hi' again without any callbacks from Barcodescanner, That's happening just when you bootstrap your application with angular not with nativescript bootstrap function

**Comment by MomenYasser** [comment]
This is stopping issue. All the app idea depends on scanning barcode. And that will make a BIG problem with my client. So i can send you the whole repository if you want. Thanks very much bro :)

**Comment by EddyVerbruggen** [comment]
I'm glad to help but don't make your problems mine to solve.

The best next option is to replicate your issue with the demo app. Or a fresh starter app with only this plugin and minimal code. If it's still happening let me know.
