### ISSUE TITLE
Bulk scan callback is not updating after routing change

### ISSUE THREAD

**Issue by pgrzeszczak-neducatio** [EddyVerbruggen/nativescript-barcodescanner#44]
Hi, I have problem with bulk scan on android (Nexus 5X, android 7.0). I need to wait for user to scan specific code. After scan I compare result with wanted code. First scan works fine, but when I change my route and reenter route with scanner, it seems like callback is not overwritten by new one, and after scan it compares result with old code.
Here is sample app to test this issue: [https://github.com/pgrzeszczak/nts-barcodescanner-test](https://github.com/pgrzeszczak/nts-barcodescanner-test)

Example steps to reproduce:
- Run app (new random string: gzddh)
- Start scan
```
JS: SCANNED: gzddh WANTED: gzddh
JS: Valid code!
```
- Go to second component
- Go to first component (new random string: uxkep)
- Start scan
```
JS: SCANNED: uxkep WANTED: gzddh
JS: Invalid code!
```

**Comment by pgrzeszczak-neducatio** [comment]
Btw. Is there any option to turn off filtering of duplicates in bulk scan?

**Comment by EddyVerbruggen** [comment]
You can disable the duplicate detection by forking this repo and commenting a line. Can you convince me there's a real-life valid usecase to do so?

About your issue: can you replicate this on a vanialla new app and/or the demo app? If so I'll take a look.

**Comment by pgrzeszczak-neducatio** [comment]
I have already provided link to simple demo app in first comment. And steps to reproduce issue in this app.
About duplicates: what if I have many products with barcode and some products can have same code. And I have to collect all products. Then I can run simple scan, then enter amount of products, and then scan another product. Or I can run bulk scan, and simply scan all codes one by one

**Comment by EddyVerbruggen** [comment]
Yeah I meant using the official demo linked to from the readme (first link on the page).

Are you aware that if you don't suppress duplicates then when your camera is "filming" the barcode it would immediately report it (possibly) 8 times in a second? That may break your usecase. Perhaps you need to only allow duplicates in case a different barcode was scanned in between?

**Comment by pgrzeszczak-neducatio** [comment]
Yes, I can reproduce issue on your demo app. When I start doContinuousScanMax3 for first time, it works ok, but second run don't clean 'count' variable. Logs:
```
JS: QR_CODE: code1 (count: 1)
JS: QR_CODE: code2 (count: 2)
JS: QR_CODE: code3 (count: 3)
JS: QR_CODE: code4 (count: 4)
JS: QR_CODE: code5 (count: 5)
JS: QR_CODE: code6 (count: 6)
```
I also can not scan 'code1' in second run. It looks like callback is not replaced at all, and preserve array of duplicates between different runs.
This is strange, because i have added some logs to your code and I can see that `self.broadcastManager.unregisterReceiver(self.onScanReceivedCallback);` id called after stop.

**Comment by EddyVerbruggen** [comment]
Looking into it because that should not happen.

**Comment by EddyVerbruggen** [comment]
Please check the current version in GitHub, it has a new `reportDuplicates` property you can set to `true` (check the updated readme as well). The problem with that counter has also been fixed.

**Comment by pgrzeszczak-neducatio** [comment]
Callback is still not correctly replaced. Run doContinuousScan, scan some codes, then run doContinuousScanMax3, and you will see in console, that old callback is still in use (which logs code without count). New callback, with stopping after third scan, is ignored. Maybe this is some issue with tns-android?

**Comment by EddyVerbruggen** [comment]
You're right - should also be fixed now. It's a bit odd it behaves like this - wouldn't expect that based on the code (and iOS doesn't either). Can you please check again?

**Comment by pgrzeszczak-neducatio** [comment]
Thanks! Now everything works

**Comment by EddyVerbruggen** [comment]
Thanks for the repeated tests!

**Comment by pgrzeszczak-neducatio** [comment]
Can you publish version 2.1.2 to npm?

**Comment by EddyVerbruggen** [comment]
Good call. It's up now!
