### ISSUE TITLE
 angular 2 can not set reportDuplicates :false  

### ISSUE THREAD

**Issue by yi5915** [EddyVerbruggen/nativescript-barcodescanner#45]
I use angular 2 and set reportDuplicates: false , but  display message   , dose not exist in type "ScanOptions" ,  I source code is  
this.barcodeScanner.scan({ 
        formats: "QR_CODE",
    // this callback will be invoked for every unique scan in realtime!
      continuousScanCallback:  (result) =>
    {
      this.count++;      
      console.log(result.format + ": " + result.text + " (count: " + this.count + ")");
      this.scantext = result.text;
      alert("count" + this.count + result.text);
      if (this.count == 3) 
      {
        this.barcodeScanner.stop();
       }
     }  ,reportDuplicates: false
   } )
   .then(
         (result) => {
        console.log("We're now reporting scan results in 'continuousScanCallback'");
         alert("scan" + result.text);
        this.scantext = result.text;
      
      },
       (error) => {
        alert("No scan: " + error);
        console.log("No scan: " + error);
      }
    );    
  }

**Comment by EddyVerbruggen** [comment]
Hi,

Which version of the plugin do you use? The latest from GitHub, or npm? This feature is not on npm yet..

**Comment by EddyVerbruggen** [comment]
Upgrade to 2.1.2 (on npm now) and you should be good.

**Comment by yi5915** [comment]
thanks .
