### ISSUE TITLE
make type script happy with barcodescanner.d.ts

### ISSUE THREAD

**Issue by leocrawf** [EddyVerbruggen/nativescript-barcodescanner#47]
I am using nativescript but having issues in the latest version because the 
/// <reference path="./node_modules/nativescript-barcodescanner/barcodescanner.d.ts" /> 
file no longer exists in nod_ modules folder. Therefore I do not know how to tell the references.d.ts file where to look for barcode-scanner. Is there another another file that can be used for type script reference?

**Comment by EddyVerbruggen** [comment]
As far as I understood that line can be removed since [this line](https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/master/package.json#L6) should tell TS what file to use. But that may depend on your TS version.

**Comment by leocrawf** [comment]
Thanks you for the quick response. I tried it and it did not work. I have to revert to version 1.3.5 which has a <reference path="./node_modules/nativescript-barcodescanner/barcodescanner.d.ts" />. If I try using the latest version it will not compile becuase there is no reference to 
<reference path="./node_modules/nativescript-barcodescanner/barcodescanner.d.ts" />.

**Comment by EddyVerbruggen** [comment]
Oh shoot, you're right! It's called `index.d.ts` these days.. let me fix this and quickly release a 2.1.3 version.

**Comment by leocrawf** [comment]
Hello,

I now have an issue where I cannot get access to scan function.

import { Component, Inject } from '@angular/core';
import {BarcodeScanner} from 'nativescript-barcodescanner';


@Component({
    selector: "my-app",
    templateUrl: "app.component.html",
})
export class AppComponent {
public scan() {
        BarcodeScanner.scan({
            cancelLabel: "Stop scanning",
            message: "Go scan something",
            preferFrontCamera: false,
            showFlipCameraButton: false
        }).then((result) => {
            alert(result.text);
        });
    }
}

**Comment by EddyVerbruggen** [comment]
Can you try it [like this](https://github.com/EddyVerbruggen/nativescript-barcodescanner#typescript)?

**Comment by joeskeen** [comment]
@leocrawf you have to have an instance of `BarcodeScanner` before calling the `scan` function.  `BarcodeScanner` is a `class`, and with Angular (as I see in your example code), you can use dependency injection to provide the instance of the class, see https://github.com/EddyVerbruggen/nativescript-barcodescanner#usage-with-nativescript-angular . If you don't want to use DI, you still will have to `new` up an instance before using it.

**Comment by leocrawf** [comment]
@joeskeen thanks for the explanation.
