### ISSUE TITLE
Trying to access/implement AVCaptureFocusMode

### ISSUE THREAD

**Issue by trevordowdle** [EddyVerbruggen/nativescript-barcodescanner#48]
Hello,

Thank you for this nativescript implementation.  One issue I am having is that once I get a barcode into view it takes 1 - 1.5 seconds to focus the camera and successfully process the barcode..

I would like to see if I could tinker with some native features to see if I can get quicker performance.

One thing i'm particular interested in trying is the [autoFocusRangeRestriction: AVCaptureAutoFocusRangeRestriction](https://developer.apple.com/reference/avfoundation/avcapturedevice/1624622-autofocusrangerestriction)

I have been trying to look at the how the plugin code is exposing the native ios api's however I'm struggling to come to grips with how this is done.

Can anyone show me an example how I can expose/edit this variable?

Thank you.

**Comment by EddyVerbruggen** [comment]
Sounds pretty interesting! Seems like a method similar to this one: https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/master/barcodescanner.ios.ts#L106-L112

Let me know if that works, otherwise I'll have to change the underlying framework.

**Comment by trevordowdle** [comment]
This works, thank you!  

The results are hard to quantify, without further testing but it does seem to make scanning quicker and reduce/eliminate cases where it takes the camera a long time to focus.

Here is an [Overview](https://developer.apple.com/reference/avfoundation/avcaptureautofocusrangerestriction)

Additionally Apple does recommend setting the Range restriction to near for machine reading (scanning) applications. ([Reference](https://developer.apple.com/reference/avfoundation/avcaptureautofocusrangerestriction/avcaptureautofocusrangerestrictionnear)

```
    this._test = function () {
            var device = AVCaptureDevice.defaultDeviceWithMediaType(AVMediaTypeVideo);
            device.lockForConfiguration();
            device.autoFocusRangeRestriction = AVCaptureAutoFocusRangeRestrictionNear;
            //device.autoFocusRangeRestriction = AVCaptureAutoFocusRangeRestrictionNone;
            console.log(device.autoFocusRangeRestriction);
            device.unlockForConfiguration();
    };
```

**Comment by EddyVerbruggen** [comment]
Supercool! Thanks for testing this out, I think that's a nice default for a future version.

**Comment by trevordowdle** [comment]
You bet, sounds good!

**Comment by MuhammadTahir92** [comment]
@EddyVerbruggen  this link is not working please check
https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/master/barcodescanner.ios.ts#L106-L112

**Comment by EddyVerbruggen** [comment]
@MuhammadTahir92 It was probably a hint about locking for configuration, so: https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/2ce4a99208e53be42174e5a0db7c500c523db1eb/src/barcodescanner.ios.ts#L132-L137
