### ISSUE TITLE
Error after scan, Android, Nativescript 2.4

### ISSUE THREAD

**Issue by pgrzeszczak** [EddyVerbruggen/nativescript-barcodescanner#50]
Hi, current version of barcodescanner does not work on android, when using nativescript 2.4. The problem is line [https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/master/barcodescanner.android.ts#L182](https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/master/barcodescanner.android.ts#L182)
`TypeError: Cannot set property currentContext of [object Object] which has only a getter`

When I removed this line in locally installed barcodescanner, it seems to work fine

**Comment by EddyVerbruggen** [comment]
Thanks for letting me know! It's a stupid hack anyway and I hope recent {N} versions make that line obsolete as you seem to have seen.

**Comment by EddyVerbruggen** [comment]
I can confirm that with {N} 2.3.0 the hack was required for the dialogs module to work after scanning, but with {N} 2.4.0 this was fixed (making the hack that was removed with this PR no longer required). 🎉
