### ISSUE TITLE
Only a question: scan speed

### ISSUE THREAD

**Issue by demym** [EddyVerbruggen/nativescript-barcodescanner#55]
Hi Eddie, 

i have successfully implemented your barcode plugin into my nativescript app. Anyway, the reactivity of the plugin in a nativescript app seems a bit slow; i have also tried the cordova based plugin, and that seems to respond more quickly, and also forgives more than the NS one in respect to positioning, light, etc.

Are there some parameters that i can touch to vary the reactivity of the scan ? I really would like to develop the app in nativescript, but for now, due to this problem, i am stuck into the cordova one, and after discovering NS this is a bit frustrating...

Not a real issue, only didn't know where to ask you this.

Thanks very much in advance

**Comment by EddyVerbruggen** [comment]
Interesting question as both use the ([this](https://github.com/EddyVerbruggen/barcodescanner-lib-aar#the-generated-aar-is-used-in)) same library on Android. Unless you're using an old version of the Cordova plugin. Ultimately it's Google's ZXing library, perhaps there's something in there that we can tweak. Is there any specific code that's slow when scanned?

**Comment by demym** [comment]
No Ed, i have no specific code; i tried both the solutions with the minimal code required by the samples to make them work. But, by a matter of fact, the cordova one decodes the barcodes with more ease... with the NS one the same barcodes require much time (and also attention in pointing them with firm hand) to have a successfull acquisition....

Wouldn't want to do cordova stuff anymore (especially having NS available)... but... anyway thanks very much

**Comment by demym** [comment]
Hi, is there a way to show the red line into the scanning area ? (as it happens into the Cordova version of the plugin ?) 

Thanks in a

**Comment by memphisvl** [comment]
Same here, the scan process feels a bit too slow and accurate positioning is required as well. Lack of scan window configuration is another issue.

**Comment by EddyVerbruggen** [comment]
Move to https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/ML_KIT.md#barcode-scanning for better performance and more UI flexibility.
