### ISSUE TITLE
Running demo does not work

### ISSUE THREAD

**Issue by E-P1983** [EddyVerbruggen/nativescript-barcodescanner#57]
Whenever I try to setup the quick demo as mentioned in the readme I get the follow errors:

```
error TS6053: File 'node_modules/tns-platform-declarations/tns-core-modules/android17.d.ts' not found.
error TS6053: File 'node_modules/tns-platform-declarations/tns-core-modules/ios/ios.d.ts' not found.
error TS6053: File 'node_modules/tns-platform-declarations/tns-core-modules/org.nativescript.widgets.d.ts' not found.
```

It seems there the package is no longer in NPM or not needed. I don't know how to solve it since I'm very new in this field :)

**Comment by EddyVerbruggen** [comment]
Running `npm install` should sort that out.. otherwise Google a bit as it's not plugin-related really.
