### ISSUE TITLE
RouterExtensions.navigate not working after scan.

### ISSUE THREAD

**Issue by cristhianp** [EddyVerbruggen/nativescript-barcodescanner#58]
Hello, I had added this great plugin in my app. The scan work fine but I have two little problems. 

First, after scan, the page is freeze for around 5 second and I can’t understand why. And second, if I insert a ‘RouterExtensions.navigate’ to other page inside ‘then’ function it’s not work.

**Comment by EddyVerbruggen** [comment]
Not sure, but can you add a timeout in `then` so you're sure the scanner animation has finished before any other transition (routing) kicks in?
