### ISSUE TITLE
Plugin does not work with AppBuilder

### ISSUE THREAD

**Issue by f1ana** [EddyVerbruggen/nativescript-barcodescanner#6]
When using Telerik AppBuilder, installing the plugin appears to be successful, but the deployed application cannot find the module.
Error message is:  Module "nativescript-barcodescanner" not found

Using other plugins within AppBuilder work correctly.

**Comment by fama0** [comment]
I've contacted Telerik and was told that the current Companion app is not compatible with plugins. Supposedly they would be fixing that in April. The current workaround is to build the project as an app package to test plugins.
