### ISSUE TITLE
Keyboard cover the text field after launch barcodescanner

### ISSUE THREAD

**Issue by kentplaza** [EddyVerbruggen/nativescript-barcodescanner#68]
I found after launch the barcode scanner, then following screen's text field will be cover by the keyboard if particular text field at the bottom.

**Comment by EddyVerbruggen** [comment]
Can you share a project reproducing this issue? Feel free to reopen once you have it.

**Comment by kentplaza** [comment]
Fine now. the prob cause by different reason.
Now work fine for android after update to 2.3.2
