### ISSUE TITLE
Android 6.0.1 Barcode scanner image reversed.

### ISSUE THREAD

**Issue by TheOriginalJosh** [EddyVerbruggen/nativescript-barcodescanner#7]
it's happening on my Nexus 5x, but not on my wife's Note 4(running Lollipop)

**Comment by TheOriginalJosh** [comment]
it appaers that the zxing library needs updated? here is a related issues i found.
http://github.com/zxing/zxing/issues/484

**Comment by EddyVerbruggen** [comment]
Hi, I've just updated the ZXing library (along with some other things) - can you confirm this is indeed fixed?

**Comment by TheOriginalJosh** [comment]
Verified that it is fixed in version 1.3.1 on my Nexus 5x. Thank you @EddyVerbruggen1

**Comment by EddyVerbruggen** [comment]
That's great! Thanks for testing this so quickly.
