### ISSUE TITLE
null is not an object (evaluating 'device.autoFocusRangeRestrictionSupported')

### ISSUE THREAD

**Issue by bijeebuss** [EddyVerbruggen/nativescript-barcodescanner#70]
I'm getting this error when I try to do a scan
```
Error in barcodescanner.scan: TypeError: null is not an object (evaluating 'device.autoFocusRangeRestrictionSupported')
```
Im using the code example from the readme and angular2. 
tns version is 2.4.2
typescript 2.0.10

**Comment by EddyVerbruggen** [comment]
What's the device you're testing on (simulator perhaps?), and what's the command you're using to start the app (livesync perhaps?).

**Comment by bijeebuss** [comment]
yes it is an iOS emulator for an iPhone 6. Im using the visual studio code plugin for native script to launch on the simulator which runs `tns debug ios --no-client` but I believe I'm getting the same error when i run `tns run ios --emulator` do I need to run it on an actual device?

**Comment by EddyVerbruggen** [comment]
Yes as the sim doesn't have a camera. You should use `available` to check capabilities as the implementation is exactly checking for that thing being null: https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/master/barcodescanner.ios.ts#L122-L126
