### ISSUE TITLE
Android zxing library

### ISSUE THREAD

**Issue by votiakov** [EddyVerbruggen/nativescript-barcodescanner#71]
Hello, @EddyVerbruggen !

Thank you for the plugin. 

I need to create my own version of native scanner, because I need some heavy changes - to both layout and scanner logic.

Could you please tell me what fork of zxing did you use to build the .aar library? Or maybe you have the source code of  barcodescanner-release-2.1.2.aar and can provide it to me. I will be very grateful. 

Thanks

**Comment by EddyVerbruggen** [comment]
Sure, it's open source as well of course. Here's the details: https://github.com/EddyVerbruggen/barcodescanner-lib-aar/blob/master/README.md

Good luck!

**Comment by votiakov** [comment]
Thank you! Have a nice day!
