### ISSUE TITLE
iOS app is crashing : Can't find variable: QRCodeReaderDelegate

### ISSUE THREAD

**Issue by sam0829** [EddyVerbruggen/nativescript-barcodescanner#72]
Hello, we have integrated this library in our project. This was working fine until yesterday on both Android & iOS. but now when we try to run the iOS app, it crashes instantly after the splashscreen & console shows this error : 
`/app/tns_modules/nativescript-barcodescanner/barcodescanner.js:232:67: JS ERROR ReferenceError: Can't find variable: QRCodeReaderDelegate`

Any help on this please?

PS : I already have checked [https://github.com/EddyVerbruggen/nativescript-barcodescanner/issues/27](url) & have tried to remove the platform / re adding it multiple times & it doesn't help. I run the app with tns run ios --device <DeviceID> & still facing the issue.

PS1 : I tried to remove this plugin & re-add it with following command
`tns plugin add nativescript-barcodescanner`

it fails every time with this error
```
The package @angular/compiler@2.2.1 does not satisfy its siblings' peerDependencies requirements!
Cannot read property '0' of undefined
```
as expected I couldn't see the nativbescript-barcodescanner in node_modules,
So I tried to install by following command,

npm install nativescript-barcodescanner --save
It also gave similar error but I was able to see the module inside node_modules.

Now, while I run the app, I can see the line like preparing nativescript-barcodescanner for iOS & I can confirm that this module exists in platform/iOS.

But then after it runs on iOS device, the app crashes saying
`/app/tns_modules/nativescript-barcodescanner/barcodescanner.js:232:67: JS ERROR ReferenceError: Can't find variable: QRCodeReaderDelegate`

I tried to run the app on iPad & iPhone 7 but it crashes with similar error

**Comment by EddyVerbruggen** [comment]
Did this by any chance coincide with an upgrade to {N} 2.5.0?

**Comment by sam0829** [comment]
No I don't think so, we haven't upgraded {N} to 2.5.0 yet. we have 2.4.2 currently.

**Comment by EddyVerbruggen** [comment]
How do you run your project in iOS (CLI command)?

**Comment by sam0829** [comment]
from Visual Studio Code's terminal, i use "tns run iOS --device --deviceId"

**Comment by EddyVerbruggen** [comment]
Can you share your project with me perhaps?

**Comment by sam0829** [comment]
I am sorry but that is not possible for me :( I am now trying 2 things,
1) using the CLI command from iOS terminal instead of Visual Studio Code's
2) making a sample app with this library & check if it runs or not.

I'll update you for both.

btw I also noticed one more line in exception :
`CONSOLE LOG file:///app/tns_modules/nativescript-globalevents/globalevents.js:98:16: Handler onNavigatedTo navigatedTo
`

& here's the full error
`CONSOLE LOG file:///app/tns_modules/nativescript-globalevents/globalevents.js:98:16: Handler onNavigatedTo navigatedTo
*** Fatal JavaScript exception - application has been terminated. ***
Native stack trace:
1   0x632adb -[TNSRuntime executeModule:referredBy:]
2   0xddae3 main
3   0x359f2aaf <redacted>
JavaScript stack trace:
1   @file:///app/tns_modules/nativescript-barcodescanner/barcodescanner.js:232:67
JavaScript error:
file:///app/tns_modules/nativescript-barcodescanner/barcodescanner.js:232:67: JS ERROR ReferenceError: Can't find variable: QRCodeReaderDelegate`

**Comment by EddyVerbruggen** [comment]
That second options would be great!

**Comment by sam0829** [comment]
It seems like something was corrupted or messed up in NativeScript. Even the simple Hello world was not running. It was crashing immediately after opening. So we upgraded {N} 2.5 & it seems to solve the issue. Thanks for your quick response :)
