### ISSUE TITLE
Crash can occur in Android runtimes because of missing AndroidManifest settings

### ISSUE THREAD

**Issue by NathanaelA** [EddyVerbruggen/nativescript-barcodescanner#77]
I have error logging for apps out in the wild and I just got this:

> Error: The application crashed because of an uncaught exception.  at Error (native) android.content.ActivityNotFoundException: Unable to find explicit activity class {com.mastertechapps.XXX/com.google.zxing.client.android.HelpActivity}; have you declared this activity in your AndroidManifest.xml?"

See this code:
https://github.com/EddyVerbruggen/barcodescanner-lib-aar/blob/e8fed10020f06b9de0ebadcbeea408175a96a94a/barcodescanner/src/main/java/com/google/zxing/client/android/CaptureActivity.java#L410

Your https://github.com/EddyVerbruggen/nativescript-barcodescanner/blob/master/platforms/android/AndroidManifest.xml should have these additional activities defined or these activities should be removed from the plugin source code so they can't get started.

**Comment by EddyVerbruggen** [comment]
Interesting issue! I did not intend the help activity to be started anyway.. any idea what would cause it? If not I'll investigate.

**Comment by NathanaelA** [comment]
I believe they must have triggered the menu somehow in the barcode scanner; and one of the options is probably help.   I haven't actually tried duplicating it; I just noticed the call stack; and looked into the plugin HOW it could have happened.  ;-)

**Comment by EddyVerbruggen** [comment]
Thanks for the details 👍

**Comment by EddyVerbruggen** [comment]
Removed the menu entirely in 2.4.1.
