### ISSUE TITLE
No scan. TypeError: Cannot read property 'zxing' of undefined

### ISSUE THREAD

**Issue by dontuta** [EddyVerbruggen/nativescript-barcodescanner#8]
Hi,

I'm new to NativeScript and I'm trying to use this module. but I get this "No scan. TypeError: Cannot read property 'zxing' of undefined" whenever I try to use it.

I have already looked into these two issues, but they didn't help. I'm running the plugin's 1.3.10 version.
https://github.com/EddyVerbruggen/nativescript-barcodescanner/issues/4
https://github.com/EddyVerbruggen/nativescript-barcodescanner/issues/1

thanks

**Comment by carvarr** [comment]
I have same issue and I'm using the 1.3.10 version too. can someone help ?

**Comment by EddyVerbruggen** [comment]
Oddly there has never been a 1.3.10 version. I just pushed 1.3.0 to npm.
