### ISSUE TITLE
nativescript-barcodescanner in NS 3.0 RC

### ISSUE THREAD

**Issue by Cae2** [EddyVerbruggen/nativescript-barcodescanner#80]
Hello!
Im testing the new RC 3.0 and cannot compile with nativescript-barcodescanner.

I was reading the 3.0 changelog and it says that **"The camera module is removed. Use nativescript-camera plugin instead."**

There is a quick fix for this or should I wait for a future version of nativescript-barcodescanner plugin?

thanks!

**Comment by EddyVerbruggen** [comment]
This plugin doesn't depend on the camera plugin AFAIK, but I'm sure there's something that needs to be changed for 3.0. Will do before the final release comes out.

**Comment by Cae2** [comment]
@EddyVerbruggen thanks!

PS: it doesnt compile, I modified barcodescanner.android.js from:
`var camera = require("camera");`
to:
`var camera = require("nativescript-camera");`

it compiles ok and I can open the camera on app and detect a barcode, but it doesnt "run" the .then method..

**Comment by EddyVerbruggen** [comment]
Thx for the details!

**Comment by celso-wo** [comment]
@Cae2, I made few adjustment and it's working now.
See my changes here:
https://github.com/EddyVerbruggen/nativescript-barcodescanner/compare/master...celso-wo:master

It's just temporary fix until the NativeScript 3 version out.
you can install using this command:

`npm install git+https://github.com/celso-wo/nativescript-barcodescanner.git --save`

**Comment by Cae2** [comment]
@celso-wo wow thats nice!

I will test it tomorrow and tell you about it, thank you!

**Comment by EddyVerbruggen** [comment]
@celso-wo I could change it myself but would you be willing to do a PR?

**Comment by Cae2** [comment]
it works with your fix Celso, thank you!

PS: since I have not tested barcodescanner before 3.0 RC (Im new on NS) I'm with one issue after scanner a barcode, Im returning the result.text promisse to a local variable and binding the value to a <SearchBar text>. It works and the EAN13 value fill the search bar. But what I noticed is that after the bar is filled, the app "freezes" about 1 or 2 seconds, just after that I can submit it... but since the barcode plugin already done its job at this point, I think that this is related to nativescript itself, just posting it here to check if someone already experienced this.. thanks

**Comment by EddyVerbruggen** [comment]
I've inlined the code of the camera plugin (1 line of code really), so there is no longer a dependency in plugin version 2.5.0. Which means this plugin should now be compatible with any {N} version including 3.x.
