### ISSUE TITLE
Promise not resolved when scanning a code right after the scanner opens. (IOS only)

### ISSUE THREAD

**Issue by nevizade** [EddyVerbruggen/nativescript-barcodescanner#83]
Hi all,

when opening the scanner in iOS where the camera of the device is directly pointed to a qr code, the scanner recognizes the code and closes without an error but also without resolving the promise. But if you wait for a second and scan the code then, the promise is beeing resolved. 

I tested this on iPhone 5s/6SE/6/7/7Plus all around iOS 9-10. On Android it is working just fine. 

Any ideas what it can be?

**Comment by EddyVerbruggen** [comment]
That doesn't match my experience. Can you reproduce that with the demo app (`/demo` folder in this repo) as well? And if so, can you share the code you're scanning, so we're on exactly the same page? Thx!

**Comment by nevizade** [comment]
Interesting it is not happening in the demo app.. I am using it with angular2 and some other plug-ins. Let me try the groceries sample..

regarding sharing code: I can share once i reproduce the problem on a different app.

Thanks for your help.

**Comment by nevizade** [comment]
Ok, there appearently has to be a timeout within the promise, else it can be ignored. Not happening on Android, just for iOS.

Also i could reproduce the problem in the demo app. If you set the timeout of the alert function within the promise to something small, it fails there too.

Is this a bug @EddyVerbruggen ?

Best

**Comment by EddyVerbruggen** [comment]
Depends. Is your issue just with showing the alert? Did you try console.log instead?

**Comment by nevizade** [comment]
My issue is to process the result of scanning. Now i ended up wrapping the whole function in a timeout.

**Comment by EddyVerbruggen** [comment]
Can you share the code that works and does not work? Just want to make sure we're on the same page here.

**Comment by nevizade** [comment]
`this.barcodeScanner.scan({
      formats: "QR_CODE, EAN_13",
      cancelLabel: "EXIT. Also, try the volume buttons!", // iOS only, default 'Close'
      cancelLabelBackgroundColor: "#333333", // iOS only, default '#000000' (black)
      message: "Use the volume buttons for extra light", // Android only, default is 'Place a barcode inside the viewfinder rectangle to scan it.'
      preferFrontCamera: front,     // Android only, default false
      showFlipCameraButton: flip,   // default false
      showTorchButton: torch,       // iOS only, default false
      torchOn: false,               // launch with the flashlight on (default false)
      resultDisplayDuration: 500,   // Android only, default 1500 (ms), set to 0 to disable echoing the scanned text
      orientation: orientation,     // Android only, default undefined (sensor-driven orientation), other options: portrait|landscape
      beepOnScan: true,             // Play or Suppress beep on scan (default true)
      openSettingsIfPermissionWasPreviouslyDenied: true // On iOS you can send the user to the settings app if access was previously denied
    }).then(
      function(result) {
        console.log("--- scanned: " + result.text);
        // Note that this Promise is never invoked when a 'continuousScanCallback' function is provided
        setTimeout(function() {
          // if this alert doesn't show up please upgrade to {N} 2.4.0+
          alert({
            title: "Scan result",
            message: "Format: " + result.format + ",\nValue: " + result.text,
            okButtonText: "OK"
          });
        }, 500);
      },
      function(errorMessage) {
        console.log("No scan. " + errorMessage);
      }
    );`


This one works, but when i take out the setTimeout, it doesn't fire if the code is "scanned too fast". looks like this:

`this.barcodeScanner.scan({
      formats: "QR_CODE, EAN_13",
      cancelLabel: "EXIT. Also, try the volume buttons!", // iOS only, default 'Close'
      cancelLabelBackgroundColor: "#333333", // iOS only, default '#000000' (black)
      message: "Use the volume buttons for extra light", // Android only, default is 'Place a barcode inside the viewfinder rectangle to scan it.'
      preferFrontCamera: front,     // Android only, default false
      showFlipCameraButton: flip,   // default false
      showTorchButton: torch,       // iOS only, default false
      torchOn: false,               // launch with the flashlight on (default false)
      resultDisplayDuration: 500,   // Android only, default 1500 (ms), set to 0 to disable echoing the scanned text
      orientation: orientation,     // Android only, default undefined (sensor-driven orientation), other options: portrait|landscape
      beepOnScan: true,             // Play or Suppress beep on scan (default true)
      openSettingsIfPermissionWasPreviouslyDenied: true // On iOS you can send the user to the settings app if access was previously denied
    }).then(
      function(result) {
        console.log("--- scanned: " + result.text);
        // HERE IS THE ALERT WITHOUT TIMEOUT
         alert({
            title: "Scan result",
            message: "Format: " + result.format + ",\nValue: " + result.text,
            okButtonText: "OK"
          });       
      },
      function(errorMessage) {
        console.log("No scan. " + errorMessage);
      }
    );`

**Comment by EddyVerbruggen** [comment]
Just to be sure, that line "--- scanned:": is that always logged?

**Comment by nevizade** [comment]
depends on what the function there is. When there is an alert, it fires anyway, but if the function is a bit more complex it just does it from time to time.

**Comment by EddyVerbruggen** [comment]
I don't really understand your answer, sorry.

The reason I asked is: the alert may not show if there's another view being shown (the barcode scanner view in this case). That's an iOS limitation. So I'm trying to figure out if this is a plugin issue or just an issue of the alert not showing because it's blocked by the scanner UI.

**Comment by nevizade** [comment]
Ok so let me try to explain further. If the function which is called in the promise is a complex function you have to set the timeout, otherwise it is not getting fired. i think this is because ios needs some time to first close the camera and the promise is fired before the camera is completetly closed (?). 
Anyway, setting timeout does the trick for now.
Thanks

**Comment by lakshaya22** [comment]
I installed the plugin, trying to run my project its throwing this error.
node_modules/nativescript-barcodescanner/barcodescanner-common.d.ts(1,29): error TS2306: File '/Users/lakshaya/Downloads/Android/node_modules/tns-core-modules/ui/content-view/content-view.d.ts' is not a module.
node_modules/nativescript-barcodescanner/barcodescanner-common.d.ts(2,26): error TS2307: Cannot find module 'tns-core-modules/ui/core/properties'.
