### ISSUE TITLE
Camera Auto Focus

### ISSUE THREAD

**Issue by rolandorocha** [EddyVerbruggen/nativescript-barcodescanner#9]
Hi,
I use your plugin in my App, but sometimes it's not easy scan some barcodes. I think if we disabled the camera auto focus we get some fasteness. Do you know how to do this? What do you think about?

**Comment by EddyVerbruggen** [comment]
Is this on iOS or Android? I just pushed a major update for Android so please re-check if that's the platform you had trouble on.
