### ISSUE TITLE
setup issue

### ISSUE THREAD

**Issue by Mohan-Gopal** [EddyVerbruggen/nativescript-barcodescanner#95]
I am getting  below errors when I try to run setup.
 
**C:\Users\Mohan\Angular2Projects\nativescript-barcodescanner-master> npm run setup**

> nativescript-barcodescanner@2.5.4 setup C:\Users\Mohan\Angular2Projects\nativescript-barcodescanner-master
> npm i && cd demo && npm i && cd .. && npm run build && cd demo && tns plugin add .. && cd ..

npm WARN nativescript-barcodescanner@2.5.4 license should be a valid SPDX license expression
npm WARN demo No description
npm WARN demo No repository field.
npm WARN demo No license field.

> nativescript-barcodescanner@2.5.4 build C:\Users\Mohan\Angular2Projects\nativescript-barcodescanner-master
> tsc

error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'Function'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'Number'.
error TS2318: Cannot find global type 'Object'.
error TS2318: Cannot find global type 'RegExp'.
error TS2318: Cannot find global type 'String'.
barcodescanner.android.ts(57,23): error TS4055: Return type of public method from exported class has or is using private name 'Promise'.

barcodescanner.android.ts(69,33): error TS4055: Return type of public method from exported class has or is using private name 'Promise'.
barcodescanner.android.ts(77,37): error TS4055: Return type of public method from exported class has or is using private name 'Promise'.
barcodescanner.android.ts(89,18): error TS4055: Return type of public method from exported class has or is using private name 'Promise'.
barcodescanner.android.ts(111,34): error TS4055: Return type of public method from exported class has or is using private name 'Promise'.
barcodescanner.common.ts(113,18): error TS4055: Return type of public method from exported class has or is using private name 'Promise'.
barcodescanner.common.ts(114,28): error TS4055: Return type of public method from exported class has or is using private name 'Promise'.
barcodescanner.common.ts(115,32): error TS4055: Return type of public method from exported class has or is using private name 'Promise'.
barcodescanner.common.ts(116,13): error TS4055: Return type of public method from exported class has or is using private name 'Promise'.
barcodescanner.common.ts(117,29): error TS4055: Return type of public method from exported class has or is using private name 'Promise'.
barcodescanner.ios.ts(124,23): error TS4055: Return type of public method from exported class has or is using private name 'Promise'.
barcodescanner.ios.ts(130,33): error TS4055: Return type of public method from exported class has or is using private name 'Promise'.
barcodescanner.ios.ts(137,37): error TS4055: Return type of public method from exported class has or is using private name 'Promise'.
barcodescanner.ios.ts(145,18): error TS4055: Return type of public method from exported class has or is using private name 'Promise'.
barcodescanner.ios.ts(159,34): error TS4055: Return type of public method from exported class has or is using private name 'Promise'.

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "setup"
**npm ERR! node v6.10.3
npm ERR! npm  v3.10.10**
npm ERR! code ELIFECYCLE
npm ERR! nativescript-barcodescanner@2.5.4 setup: `npm i && cd demo && npm i && cd .. && npm run build && cd demo && tns plugin add .. && cd ..`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nativescript-barcodescanner@2.5.4 setup script 'npm i && cd demo && npm i && cd .. && npm run build && cd demo && tns plugin add .. && cd ..'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nativescript-barcodescanner package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i && cd demo && npm i && cd .. && npm run build && cd demo && tns plugin add .. && cd ..
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nativescript-barcodescanner
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nativescript-barcodescanner
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Mohan\Angular2Projects\nativescript-barcodescanner-master\npm-debug.log

**Comment by EddyVerbruggen** [comment]
Thanks for reporting this one, it's fixed in 2.5.5.
