### ISSUE TITLE
W/YCONFIG (32406): JSON Exception : No value for weather_effects_enabled

### ISSUE THREAD

**Issue by leocrawf** [EddyVerbruggen/nativescript-barcodescanner#97]
I am using the plugin with angular and it works well except I see this message in the terminal. W/YCONFIG (32406): JSON Exception : No value for weather_effects_enabled. It does not stop the app from running in any way but it is just annoying to see it there. I checked around but I am not seeing others report this issue. I am using the typical angular setup code that is used here: https://github.com/EddyVerbruggen/nativescript-barcodescanner#usage-with-nativescript-angular

**Comment by EddyVerbruggen** [comment]
I have no idea what "weather_effects_enabled" means in relation to this plugin.
