### ISSUE TITLE
Way to detect when the camera was closed

### ISSUE THREAD

**Issue by SamuelM333** [EddyVerbruggen/nativescript-barcodescanner#98]
First of all, thanks for the great work on this plugin. 

I need a way to detect when the camera was closed so I can run some logic afterwards. Is there any way to do that? Thanks!

**Comment by EddyVerbruggen** [comment]
With a normal scan you can just wait for `reject` to fire, but for continuous scanning, there's no current way to determine that. So I'm marking this as a feature request (for continuous scanning).

**Comment by EddyVerbruggen** [comment]
See the updated readme. 2.6.0 will be pushed to npm shortly.
